#!/usr/bin/env python3
"""Render sources.py into manifest.json, MANIFEST.md and chant_candidates.json.

    python3 build_manifest.py

fetch.py writes what it learns (resolved file URLs, licences read off the
source page, sizes) to fetched.json; this script folds that in, so rerun it
after every fetch.
"""

import json
from pathlib import Path

import sources as S

HERE = Path(__file__).resolve().parent
RECORDINGS = HERE.parent.parent / "app" / "Resources" / "Chants"
BYTES_PER_SECOND = 59 * 1024 * 1024 / (4 * 3600)  # the bundle's mono HE-AAC 32 kbps, measured


def fetched() -> dict:
    p = HERE / "fetched.json"
    return json.loads(p.read_text()) if p.exists() else {}


def build():
    got = fetched()
    pictures = []
    for p in S.PAINTINGS:
        e = dict(kind="painting", status="unverified", file_url=None, commons_file=None,
                 width=None, height=None, bytes=None, **p)
        e.update(got.get(p["imageset"], {}))
        pictures.append(e)

    existing = []
    for name, work, creator, date, collection, confidence in S.EXISTING:
        e = dict(kind="painting", imageset=name, status="unverified", identification_confidence=confidence,
                 work=work, creator=creator, date=date, collection=collection,
                 source_page=None, file_url=None, **S.PD_ART)
        if creator is None:
            e.update(licence="Probably public domain (old master), unconfirmed until the work is identified",
                     licence_url=None)
        e.update(got.get(name, {}))
        existing.append(e)
    carlo = dict(kind="photograph", **S.CARLO)

    chants = []
    for c in S.CHANTS:
        est = c["est_seconds"]
        e = dict(kind="chant", id=c["entry"]["id"], tier=c["tier"], status="unverified",
                 source_page=c["source"], creator=S.VG["creator"], licence=S.VG["licence"],
                 licence_url=S.VG["licence_url"], attribution=S.VG["attribution"],
                 estimated_seconds=est, estimated_bytes=round(est * BYTES_PER_SECOND),
                 size_is_estimate=True, note=c.get("note"))
        e.update({k: v for k, v in got.get(c["entry"]["id"], {}).items() if k != "resolved_entry"})
        encoded = RECORDINGS / f"{e['id']}.m4a"
        if encoded.exists():  # generate.py has run: the real size replaces the estimate
            e.update(encoded_bytes=encoded.stat().st_size, size_is_estimate=False)
        chants.append(e)

    manifest = {
        "_about": "Content sourced for Lumen Viae (branch claude/content-sourcing). Generated from sources.py by build_manifest.py; do not hand-edit.",
        "new_paintings": pictures,
        "existing_paintings": existing,
        "flagged": [carlo],
        "chants": chants,
        "chants_not_found": [dict(latin=a, tier=t, slot=s, finding=f) for a, t, s, f in S.NOT_FOUND],
        "fallback_sources": [dict(name=n, url=u, note=x) for n, u, x in S.FALLBACK_SOURCES],
    }
    (HERE / "manifest.json").write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n")

    candidates = {
        "_about": "Proposed additions to Tools/Chants/chants.json, in its exact schema. `status` says which have been verified (their page and Verbum Gloriae's licence page read by fetch.py); merge_chants.py appends only those. Generated by build_manifest.py; do not hand-edit.",
        "groups": S.CHANT_GROUPS_TO_ADD,
        "chants": [got.get(c["entry"]["id"], {}).get("resolved_entry", c["entry"]) for c in S.CHANTS],
        "status": {c["id"]: c["status"] for c in chants},
    }
    (HERE / "chant_candidates.json").write_text(json.dumps(candidates, ensure_ascii=False, indent=2) + "\n")

    (HERE / "MANIFEST.md").write_text(markdown(manifest))


def cell(v):
    return "—" if v in (None, "") else str(v).replace("|", "\\|").replace("\n", " ")


def markdown(m) -> str:
    out = ["# Content sourcing manifest", "",
           "**On the Mac, in one sitting** (from the repo root):", "",
           "```sh",
           "cd Tools/ContentSourcing && pip3 install pillow && python3 fetch.py && python3 merge_chants.py && cd ../Chants && python3 generate.py && cd ../ContentSourcing && python3 build_manifest.py",
           "```", "",
           "1. `python3 fetch.py`: fetches every unverified painting and chant in manifest.json, reads each licence page, "
           "writes the new imagesets, and records what it read in fetched.json. Idempotent; any licence off the allowed "
           "list fails loudly and the run exits 1, with nothing failed written to the app. Fix a failed painting with "
           "`python3 fetch.py --search <imageset>`, then `python3 fetch.py --take <imageset> \"File:…\"`.",
           "2. `python3 merge_chants.py`: appends the verified chant candidates to Tools/Chants/chants.json "
           "(`--dry-run` first to see them). Unverified ones are left out.",
           "3. `cd ../Chants && python3 generate.py`: needs `brew install ffmpeg` and macOS's afconvert; encodes only the new recordings.",
           "4. `python3 build_manifest.py`: records the real encoded sizes in the manifest.", "",
           "Generated from `sources.py` by `build_manifest.py`; edit there. Machine-readable: `manifest.json`.", "",
           "**Status:** `unverified` means named here, but no licence page has been read yet; `verified` means fetch.py "
           "read the licence on the source page and it is on the allowed list; `flagged` means the licence cannot be established. "
           "This round's session could reach no source host, so everything starts unverified.", "",
           "## New paintings", "",
           "| Imageset | Slot | Work | Creator | Date | Collection | Licence | Status |",
           "|---|---|---|---|---|---|---|---|"]
    for p in m["new_paintings"]:
        out.append("| `{}` | {} | {} | {} | {} | {} | {} | {} |".format(
            p["imageset"], cell(p["slot"]), cell(p["work"]), cell(p["creator"]), cell(p["date"]),
            cell(p["collection"]), cell(p["licence"]), p["status"]))
    out += ["", "Alternates and reasons:", ""]
    for p in m["new_paintings"]:
        out.append(f"- `{p['imageset']}`: {cell(p['why'])}" + (f" *Alternate:* {p['alternate']}." if p.get("alternate") else ""))
    out += ["", "Target format: 1600 px on the long edge, progressive JPEG, 300–800 KB; one 1x image per imageset like the existing ones.", "",
            "## Existing paintings: provenance", "",
            "Identified by eye from the bundled images. `high` = recognisable work; `medium` = likely; `low` = subject only. "
            "All are pre-1910 old masters, so PD-Art is expected; confirm each with `fetch.py --provenance`.", "",
            "| Imageset | Work | Creator | Date | Collection | Confidence |", "|---|---|---|---|---|---|"]
    for e in m["existing_paintings"]:
        out.append("| `{}` | {} | {} | {} | {} | {} |".format(e["imageset"], cell(e["work"]), cell(e["creator"]),
                                                          cell(e["date"]), cell(e["collection"]), e["identification_confidence"]))
    out += ["", "## Flagged", ""]
    for f in m["flagged"]:
        out += [f"- **`{f['imageset']}`**: {f['work']}. Creator: {f['creator']}. Licence: {f['licence']}.", "", f"  {f['note']}", ""]
    out += ["## Chant candidates (Verbum Gloriae)", "",
            f"Licence for all: {S.VG['licence']} — {S.VG['licence_url']}. Sizes are estimates at the bundle's measured "
            "rate (59 MB / 4 h ≈ 4.3 KB/s) until generate.py encodes them.", "",
            "| id | Tier | Status | Page | Est. length | Size | Note |", "|---|---|---|---|---|---|---|"]
    total = 0
    for c in m["chants"]:
        size = c.get("encoded_bytes") or c["estimated_bytes"]
        total += size
        out.append("| `{}` | {} | {} | {} | {}:{:02d} | {:.2f} MB{} | {} |".format(
            c["id"], c["tier"], c["status"], c["source_page"], c["estimated_seconds"] // 60, c["estimated_seconds"] % 60,
            size / 1048576, "" if c.get("encoded_bytes") else " (est.)", cell(c["note"])))
    out += ["", f"Growth if all are taken: {total / 1048576:.1f} MB of audio, on top of the bundle's ~59 MB (plus scores, ~60 KB each).", "",
            "## Asked for, not on Verbum Gloriae", "", "| Chant | Tier | Slot | Finding |", "|---|---|---|---|"]
    for n in m["chants_not_found"]:
        out.append(f"| {n['latin']} | {n['tier']} | {n['slot']} | {cell(n['finding'])} |")
    out += ["", "Fallbacks (to list for the manager, not to stage):", ""]
    for f in m["fallback_sources"]:
        out.append(f"- [{f['name']}]({f['url']}): {f['note']}")
    out += ["", "## Why the chants need the Mac", "",
            "The bundle's recordings are mono HE-AAC, encoded by macOS's afconvert. Linux ffmpeg 6.1 has only the LC `aac` "
            "encoder (no libfdk_aac), so generate.py cannot match the bundle there. Tools/Chants/ belongs to the Chant "
            "session: merge_chants.py only appends verified entries to chants.json, in its own layout.", ""]
    return "\n".join(out)


if __name__ == "__main__":
    build()
