//
//  TrueDevotionReaderView.swift
//  Lumen Viae
//
//  True Devotion's own title page, set the way the Spiritual Reading
//  shelf sets every book: the binding floating over its halo of Marian
//  blue, one gold act that resumes the exact chapter, the day's
//  measure, and a ruled ledger of chapters under their part headings.
//
//  The book is bundled — Faber's 1862 translation, generated by the
//  pipeline in Tools/TrueDevotion — so unlike the shelf there is
//  nothing to fetch and nothing to save for offline. Reading state is
//  owned by TrueDevotionReaderViewModel; this view presents it.
//

import SwiftUI
import SwiftData

extension TrueDevotionBook {
    /// The binding the shelf gave this book — Marian blue.
    static let bindingColor = Color(hex: "2e3d66")

    /// The id a note on a passage carries in the journal.
    static let noteBookID = "true-devotion"
}

struct TrueDevotionReaderView: View {

    // MARK: - Properties

    @Environment(\.dismiss) private var dismiss
    @Environment(\.modelContext) private var modelContext
    @Environment(UserSettings.self) private var settings

    /// Owned here and handed down explicitly, so every chapter pushed from
    /// this screen shares one instance.
    @State private var viewModel = TrueDevotionReaderViewModel()

    /// The reader's notes on this book, from the journal.
    @State private var notes: [JournalEntry] = []

    /// Which parts stand open — the part being read, seeded once.
    @State private var expandedParts: Set<Int> = []
    @State private var didSeedExpansion = false

    @State private var sheet: PageSheet?

    private enum PageSheet: String, Identifiable {
        case goal, notes
        var id: String { rawValue }
    }

    private let meter = ReadingDayMeter.shared

    let library: TrueDevotionLibrary

    init(library: TrueDevotionLibrary = .shared) {
        self.library = library
    }

    // MARK: - Body

    var body: some View {
        ZStack {
            AppColors.appGradient
                .ignoresSafeArea()

            if let book = library.book {
                content(book)
            } else {
                Text("The book could not be loaded.")
                    .font(AppFonts.bodyFont(15))
                    .foregroundColor(AppColors.textSecondary)
            }
        }
        .sheet(item: $sheet) { which in
            switch which {
            case .goal:
                ReadingGoalSheet()
                    .presentationDetents([.height(400)])
                    .presentationDragIndicator(.visible)

            case .notes:
                BookNotesSheet(notes: notes)
                    .presentationDetents([.height(520), .large])
                    .presentationDragIndicator(.visible)
            }
        }
        .navigationBarBackButtonHidden(true)
        .toolbar {
            ToolbarItem(placement: .navigationBarLeading) {
                Button(action: { dismiss() }) {
                    HStack(spacing: 6) {
                        AppIcon("ph-caret-left", size: 14)
                        Text("Back")
                            .font(AppFonts.bodyFont(16))
                    }
                    .foregroundColor(AppColors.gold)
                }
            }
        }
        .onAppear {
            viewModel.setModelContext(modelContext)
            viewModel.loadProgress()
            loadNotes()
            seedExpansion()
        }
        .alert(
            "Something went wrong",
            isPresented: Binding(
                get: { viewModel.errorMessage != nil },
                set: { if !$0 { viewModel.errorMessage = nil } }
            )
        ) {
            Button("OK", role: .cancel) { viewModel.errorMessage = nil }
        } message: {
            Text(viewModel.errorMessage ?? "")
        }
    }

    private func content(_ book: TrueDevotionBook) -> some View {
        ScrollView(showsIndicators: false) {
            LazyVStack(alignment: .leading, spacing: 0) {
                header(book)
                    .devotionalEntrance()

                primaryAct(book)
                    .padding(.horizontal, 20)
                    .padding(.bottom, 18)
                    .devotionalEntrance(delay: 0.05)

                goalSection(book)
                    .padding(.horizontal, 20)
                    .padding(.bottom, 20)
                    .devotionalEntrance(delay: 0.1)

                ledger(book)
                    .padding(.horizontal, 20)
                    .devotionalEntrance(delay: 0.15)

                if !notes.isEmpty {
                    BookNotesRow(count: notes.count) { sheet = .notes }
                        .padding(.horizontal, 20)
                        .padding(.top, 10)
                }

                sourceNote(book)
                    .padding(.horizontal, 32)
                    .padding(.top, 26)
                    .padding(.bottom, 48)
            }
        }
    }

    // MARK: - Header

    /// The binding over its halo. Title and author are said once, on
    /// the cloth.
    private func header(_ book: TrueDevotionBook) -> some View {
        VStack(spacing: 0) {
            BookCover(
                title: book.title,
                author: book.author,
                bindingColor: TrueDevotionBook.bindingColor,
                hasRibbon: viewModel.hasStartedReading
            )
            .frame(width: 136)
            .shadow(color: .black.opacity(0.55), radius: 15, y: 7)
            // As a background the halo takes none of its 540 points in
            // layout, and it scrolls away with the cover instead of
            // clinging to the viewport.
            .background {
                BookHalo(bindingColor: TrueDevotionBook.bindingColor)
            }
            .padding(.top, 18)
        }
        .frame(maxWidth: .infinity)
        .padding(.bottom, 24)
        .accessibilityElement(children: .ignore)
        .accessibilityLabel("\(book.title), \(book.author).")
    }

    // MARK: - The one gold act

    @ViewBuilder
    private func primaryAct(_ book: TrueDevotionBook) -> some View {
        let resume = viewModel.continueChapter(in: book)
        let opening = resume ?? book.chapters.first

        if let opening {
            NavigationLink {
                TrueDevotionChapterReaderView(
                    chapterID: opening.id,
                    viewModel: viewModel,
                    library: library
                )
            } label: {
                // The act block draws itself; the link only carries it.
                ContinueReadingAct(
                    kicker: viewModel.hasStartedReading ? "CONTINUE READING" : "BEGIN READING",
                    destination: opening.title,
                    fraction: chapterFraction(opening),
                    meta: actMeta(for: opening),
                    action: {}
                )
                .allowsHitTesting(false)
            }
            .buttonStyle(GoldCTAButtonStyle())
            .accessibilityLabel("Continue reading: \(opening.title)")
        }
    }

    /// How far into a chapter the marker stands, by paragraph.
    private func chapterFraction(_ chapter: TrueDevotionChapter) -> Double {
        guard viewModel.lastChapterID == chapter.id,
              !viewModel.isCompleted(chapter.id),
              !chapter.paragraphs.isEmpty else { return 0 }
        return min(max(
            Double(viewModel.lastParagraphIndex) / Double(chapter.paragraphs.count), 0
        ), 1)
    }

    /// Whether the book has been opened — and nothing more.
    ///
    /// `estimatedMinutes` is words divided by two hundred, a guess about
    /// the reader rather than a fact about anything, so it must not be
    /// set under the act as though it were a clock. The shelf's own
    /// `actMeta` refuses the same guess: it quotes a recording's length
    /// or stays quiet. True Devotion is bundled text with no recording,
    /// so here it stays quiet.
    private func actMeta(for chapter: TrueDevotionChapter) -> String? {
        viewModel.hasStartedReading ? nil : "NOT YET OPENED"
    }

    // MARK: - Today's goal

    @ViewBuilder
    private func goalSection(_ book: TrueDevotionBook) -> some View {
        VStack(alignment: .leading, spacing: 8) {
            TodaysGoalBand(
                line: meter.goalLine(for: settings.readingGoal),
                fraction: meter.fraction(toward: settings.readingGoal),
                action: { sheet = .goal }
            )

        }
    }

    // MARK: - Contents

    private func ledger(_ book: TrueDevotionBook) -> some View {
        VStack(alignment: .leading, spacing: 0) {
            Text("CONTENTS · \(book.chapters.count) CHAPTERS")
                .font(AppFonts.labelFont(10))
                .tracking(2.5)
                .foregroundColor(AppColors.gold.opacity(0.85))
                .padding(.bottom, 4)

            // The Introduction stands before the parts, ungrouped.
            let free = book.chapters.filter { $0.part == 0 }
            ForEach(free) { chapter in
                chapterRow(chapter, isLast: false)
            }

            ForEach(book.parts) { part in
                partHeader(part, in: book)

                if expandedParts.contains(part.number) {
                    let chapters = book.chapters.filter { $0.part == part.number }
                    ForEach(chapters) { chapter in
                        chapterRow(chapter, isLast: chapter.id == chapters.last?.id)
                    }
                    .padding(.bottom, 6)
                }
            }
        }
    }

    private func partHeader(_ part: TrueDevotionPart, in book: TrueDevotionBook) -> some View {
        let isOpen = expandedParts.contains(part.number)
        let chapters = book.chapters.filter { $0.part == part.number }
        let holdsCurrent = viewModel.lastChapterID.map { id in
            chapters.contains { $0.id == id }
        } ?? false

        return Button {
            if isOpen {
                expandedParts.remove(part.number)
            } else {
                expandedParts.insert(part.number)
            }
        } label: {
            HStack(spacing: 12) {
                Text(shortPartTitle(part).uppercased())
                    .font(AppFonts.labelFont(11))
                    .tracking(2.5)
                    .foregroundColor(AppColors.gold.opacity(isOpen ? 0.95 : 0.75))
                    .lineLimit(1)
                    .minimumScaleFactor(0.8)

                if holdsCurrent, !isOpen {
                    Circle()
                        .fill(AppColors.goldLight)
                        .frame(width: 5, height: 5)
                }

                Rectangle()
                    .fill(
                        LinearGradient(
                            colors: [AppColors.gold.opacity(0.3), AppColors.gold.opacity(0)],
                            startPoint: .leading,
                            endPoint: .trailing
                        )
                    )
                    .frame(height: 1)
                    .frame(minWidth: 20)

                Text("\(chapters.count)")
                    .font(AppFonts.labelFont(10))
                    .tracking(1)
                    .foregroundColor(AppColors.textSecondary.opacity(0.8))

                AppIcon(isOpen ? "ph-caret-up" : "ph-caret-down", size: 10)
                    .foregroundColor(AppColors.gold.opacity(0.6))
            }
            .padding(.vertical, 14)
            .frame(minHeight: 44)
            .contentShape(Rectangle())
        }
        .buttonStyle(.plain)
        .accessibilityLabel("\(part.title), \(chapters.count) chapters")
        .accessibilityHint(isOpen ? "Closes this part's chapters" : "Opens this part's chapters")
    }

    /// "PART I" from "Part I — On Devotion to Our Lady in General"; the
    /// full title would swallow the whole rule.
    private func shortPartTitle(_ part: TrueDevotionPart) -> String {
        part.title.components(separatedBy: " — ").first ?? part.title
    }

    private func chapterRow(_ chapter: TrueDevotionChapter, isLast: Bool) -> some View {
        let isCompleted = viewModel.isCompleted(chapter.id)
        let isCurrent = viewModel.lastChapterID == chapter.id && !isCompleted
        let markCount = viewModel.markCount(forChapter: chapter.id)

        return VStack(spacing: 0) {
            NavigationLink {
                TrueDevotionChapterReaderView(
                    chapterID: chapter.id,
                    viewModel: viewModel,
                    library: library
                )
            } label: {
                HStack(alignment: .center, spacing: 10) {
                    VStack(alignment: .leading, spacing: 3) {
                        Text(chapter.title)
                            .font(AppFonts.bodyFont(15))
                            .foregroundColor(AppColors.cream)
                            .multilineTextAlignment(.leading)
                            .fixedSize(horizontal: false, vertical: true)
                    }

                    Spacer(minLength: 8)

                    if markCount > 0 {
                        HStack(spacing: 4) {
                            MarkerRibbonShape()
                                .fill(AppColors.goldLight)
                                .frame(width: 7, height: 15)

                            Text("\(markCount)")
                                .font(AppFonts.labelFont(9))
                                .foregroundColor(AppColors.goldLight.opacity(0.9))
                        }
                    }

                    Text("\(chapter.estimatedMinutes) MIN")
                        .font(AppFonts.labelFont(9))
                        .tracking(1.2)
                        .foregroundColor(AppColors.textSecondary.opacity(0.8))
                        .fixedSize()

                    if isCurrent {
                        Circle()
                            .fill(AppColors.goldLight)
                            .frame(width: 6, height: 6)
                    } else {
                        AppIcon("ph-caret-right", size: 11)
                            .foregroundColor(AppColors.textSecondary.opacity(0.5))
                    }
                }
                .padding(.vertical, 12)
                .padding(.leading, 14)
                .frame(minHeight: 44)
                .contentShape(Rectangle())
                .overlay(alignment: .leading) {
                    Rectangle()
                        .fill(isCompleted ? AppColors.gold.opacity(0.45) : Color.clear)
                        .frame(width: 2)
                        .padding(.vertical, 8)
                        .accessibilityHidden(true)
                }
            }
            .buttonStyle(.plain)
            .accessibilityElement(children: .ignore)
            .accessibilityLabel(spokenLabel(chapter, isCompleted: isCompleted, isCurrent: isCurrent))
            .accessibilityAddTraits(isCurrent ? [.isSelected] : [])

            if !isLast {
                Divider()
                    .background(AppColors.gold.opacity(0.15))
            }
        }
    }

    private func spokenLabel(
        _ chapter: TrueDevotionChapter,
        isCompleted: Bool,
        isCurrent: Bool
    ) -> String {
        var parts = [chapter.title]
        if isCurrent { parts.append("where you are") }
        else if isCompleted { parts.append("read") }
        parts.append("\(chapter.estimatedMinutes) minutes")
        return parts.joined(separator: ". ")
    }

    /// The part being read stands open on arrival; without one, the
    /// first. Seeded once.
    private func seedExpansion() {
        guard !didSeedExpansion, let book = library.book else { return }
        didSeedExpansion = true

        if let id = viewModel.lastChapterID,
           let chapter = book.chapter(id: id), chapter.part > 0 {
            expandedParts = [chapter.part]
        } else if let first = book.parts.first {
            expandedParts = [first.number]
        }
    }

    // MARK: - Notes

    private func loadNotes() {
        let id = TrueDevotionBook.noteBookID
        let descriptor = FetchDescriptor<JournalEntry>(
            predicate: #Predicate { $0.bookID == id },
            sortBy: [SortDescriptor(\.createdAt, order: .reverse)]
        )
        notes = (try? modelContext.fetch(descriptor)) ?? []
    }

    // MARK: - Source Note

    private func sourceNote(_ book: TrueDevotionBook) -> some View {
        VStack(spacing: 6) {
            OrnamentDivider(showsCross: false)
                .padding(.horizontal, 40)
                .padding(.bottom, 6)

            Text(book.translator)
                .font(AppFonts.italicFont(12))
                .foregroundColor(AppColors.textSecondary)
                .multilineTextAlignment(.center)

            Text(book.sourceNote)
                .font(AppFonts.italicFont(12))
                .foregroundColor(AppColors.textSecondary.opacity(0.7))
                .multilineTextAlignment(.center)
        }
        .frame(maxWidth: .infinity)
    }
}

// MARK: - Preview

#Preview {
    NavigationStack {
        TrueDevotionReaderView()
    }
    // The pushed chapter reader reads UserSettings from the environment,
    // so without this the preview traps as soon as a chapter is opened.
    .environment(UserSettings.shared)
    .modelContainer(for: [TrueDevotionReadingProgress.self, JournalEntry.self])
}
