#!/usr/bin/env python3
"""Generate VERIFICATION.md — the checklist for proofing the bundled book.

    python3 Tools/TrueDevotion/verify_book.py

Reads the generated app/Resources/TrueDevotionBook.json and writes a document
listing, for every chapter, the counts and the exact opening and closing
sentences to compare against the page scans. Also re-runs the integrity checks
so the document always states the current state rather than a remembered one.
"""

import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, '..', '..'))
BOOK_JSON = os.path.join(REPO, 'app', 'Resources', 'TrueDevotionBook.json')
CHAPTERS_DIR = os.path.join(HERE, 'chapters')
OUT = os.path.join(HERE, 'VERIFICATION.md')

SCAN_URL = 'https://archive.org/details/treatiseontruede00grig'

# Readings the proofreading pass could not settle from the scan alone. Each is
# (chapter stem, phrase as shipped, what to check). Add to this list whenever a
# judgement call is made, so the next person can re-examine it.
UNCERTAIN = [
    ('introduction', 'hiding herself, even from herself; as well as from every other creature',
     'Semicolon looks wrong for the sense; kept as printed. Confirm against the page.'),
    ('necessity', 'they will deliver themselves to her, body and soul',
     'Scan is garbled here. "her" was chosen over "Mary" as the more usual Faber wording.'),
    ('necessity', 'Et scient quia Dominus dominabitur Jacob',
     'Kept "Dominus" as printed; the Vulgate (Ps. 58:14) and the gloss below it read "Deus".'),
    ('necessity', 'My Well-beloved and My Spouse',
     'Hyphen reconstructed after the de-hyphenation pass; compare the printed line.'),
]

SCAN_DAMAGE = re.compile(r'[<>|@\\{}~^]|\s[a-z]\s[a-z]\s|\.\.\s')
PAGE_FURNITURE = re.compile(r'TRUE DEVOTION TO\b|THE BLESSED VIRGIN\.\s*\d|Digitized by')


def sentence_at(text, first):
    """First or last sentence of a paragraph, trimmed for the table."""
    parts = [s.strip() for s in re.split(r'(?<=[.!?”])\s+', text) if s.strip()]
    if not parts:
        return text[:120]
    return parts[0] if first else parts[-1]


def main():
    if not os.path.exists(BOOK_JSON):
        print('Run build_book.py first — no generated book found.')
        return 1

    with open(BOOK_JSON, encoding='utf-8') as f:
        book = json.load(f)

    parts = {p['number']: p['title'] for p in book['parts']}
    lines = []
    w = lines.append

    w('# Verifying the True Devotion text')
    w('')
    w('<!-- Generated by Tools/TrueDevotion/verify_book.py — do not edit by hand. -->')
    w('')
    w(f"**{book['title']}** — {book['author']}  ")
    w(f"{book['translator']}  ")
    w(f"{book['sourceNote']}")
    w('')
    w(f'Page scans: <{SCAN_URL}>')
    w('')

    total_words = sum(len(p['text'].split()) for c in book['chapters'] for p in c['paragraphs'])
    total_paras = sum(len(c['paragraphs']) for c in book['chapters'])
    w(f"The bundled text is **{len(book['chapters'])} chapters, {total_paras} paragraphs, "
      f"{total_words:,} words**.")
    w('')

    w('## Why this document exists')
    w('')
    w('The text was produced by optical character recognition of a 1904 printing, then')
    w('corrected. OCR fails in ways that are easy to miss when reading casually — it')
    w('turns "of" into "ot", drops a line of a Latin quotation, or leaves a running page')
    w('header stranded mid-sentence. Anything still wrong is now in front of readers who')
    w('are praying with it, so it is worth checking deliberately rather than trusting the')
    w('cleanup pass.')
    w('')
    w('This document gives you the opening and closing sentence of every chapter. Those')
    w('are where truncation shows up: if a chapter starts or ends mid-thought, text was')
    w('lost at a boundary. Read them against the scan first, then spot-check the body.')
    w('')

    w('## How to check a chapter')
    w('')
    w(f'1. Open the scan at <{SCAN_URL}> and find the chapter.')
    w('2. Compare the opening and closing sentences below. They should match the print exactly.')
    w('3. Skim the shipped text for the chapter in the app, or open')
    w('   `Tools/TrueDevotion/chapters/<id>.txt` directly.')
    w('4. Found something wrong? Edit the `.txt` file — never the generated JSON — then run:')
    w('')
    w('   ```')
    w('   python3 Tools/TrueDevotion/build_book.py')
    w('   python3 Tools/TrueDevotion/verify_book.py')
    w('   ```')
    w('')
    w('5. Tick the chapter off in the table once you have read it against the scan.')
    w('')

    w('## Chapters')
    w('')
    w('| ✓ | Chapter | Part | Paras | Words | Read |')
    w('|---|---------|------|-------|-------|------|')
    for ch in book['chapters']:
        words = sum(len(p['text'].split()) for p in ch['paragraphs'])
        minutes = max(1, -(-words // 200))
        part = 'Front' if ch['part'] == 0 else f"{ch['part']}"
        w(f"| ☐ | {ch['title']} | {part} | {len(ch['paragraphs'])} | {words:,} | {minutes} min |")
    w('')

    w('## Chapter boundaries')
    w('')
    w('Compare each pair against the printed page. A chapter that begins or ends')
    w('mid-sentence means text was dropped at the seam.')
    w('')
    for ch in book['chapters']:
        body = [p for p in ch['paragraphs'] if p['kind'] == 'text']
        if not body:
            continue
        subheads = [p['text'] for p in ch['paragraphs'] if p['kind'] == 'subheading']
        w(f"### {ch['title']}")
        w('')
        w(f"`{ch['id']}` · {parts.get(ch['part'], 'Front matter')}")
        w('')
        w(f"- **Opens:** {sentence_at(body[0]['text'], True)}")
        w(f"- **Closes:** {sentence_at(body[-1]['text'], False)}")
        if subheads:
            w(f"- **Sections:** {' · '.join(subheads)}")
        w('')

    w('## Editorial conventions applied')
    w('')
    w("- Faber's Victorian spelling is preserved as printed — *honour*, *characterise*,")
    w('  *Holy Ghost*, and his long sentences. Nothing was modernised or paraphrased.')
    w('- Latin quotations are kept in full and corrected to standard Vulgate spellings')
    w('  where the scan mangled them.')
    w('- Running page headers, catchwords, and library stamps were removed.')
    w('- Words split across a line or page break were rejoined.')
    w("- Square brackets in the text are Faber's own translator's interpolations, not")
    w('  editorial additions.')
    w('- Straight quotes were converted to typographic quotes and em dashes.')
    w('')

    w('## Readings still in doubt')
    w('')
    if UNCERTAIN:
        w('Judgement calls made where the scan was unclear. Each is worth a second look:')
        w('')
        for stem, phrase, note in UNCERTAIN:
            w(f'- **{stem}** — “{phrase}”  ')
            w(f'  {note}')
        w('')
    w('The proofreading pass covered all thirteen chapters, but its per-chapter notes')
    w('were only captured for the two listed above. The remaining chapters were')
    w('corrected without a surviving record of the judgement calls, so they deserve the')
    w('closest reading.')
    w('')

    w('## Automated checks')
    w('')
    problems = []
    for ch in book['chapters']:
        stem_path = os.path.join(CHAPTERS_DIR, f"{ch['id']}.txt")
        if not os.path.exists(stem_path):
            problems.append(f"source text missing for `{ch['id']}`")
        for para in ch['paragraphs']:
            for pattern, label in ((SCAN_DAMAGE, 'scan damage'), (PAGE_FURNITURE, 'page header')):
                for match in pattern.finditer(para['text']):
                    snippet = para['text'][max(0, match.start() - 30):match.end() + 30]
                    problems.append(f"{label} in `{ch['id']}` ¶{para['id']}: …{snippet}…")

    ids = [c['id'] for c in book['chapters']]
    if len(ids) != len(set(ids)):
        problems.append('duplicate chapter ids — reading progress would collide')

    w('Re-run with `verify_book.py`. These run over the generated JSON:')
    w('')
    w('- every chapter has its source file under `chapters/`')
    w('- no stray scan characters (`< > | @ \\ { } ~ ^`) survive')
    w('- no printed page headers are stranded inside a paragraph')
    w('- chapter ids are unique — they key each reader\'s saved progress')
    w('')
    if problems:
        w(f'**{len(problems)} issue(s) found:**')
        w('')
        for problem in problems[:40]:
            w(f'- {problem}')
    else:
        w('**All checks pass.**')
    w('')

    w('## Regenerating')
    w('')
    w('`chapters/*.txt` is the source of truth; `app/Resources/TrueDevotionBook.json` is')
    w('generated and should never be edited directly. Paragraph order within a chapter')
    w("determines each paragraph's id, and those ids are what a reader's saved place")
    w('points at — reordering or inserting a paragraph shifts everyone below it. Adding')
    w('to the end of a chapter is safe.')
    w('')
    w('Chapter ids in `build_book.py` are likewise persisted in reading progress and must')
    w('never be renamed once shipped.')
    w('')

    with open(OUT, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))

    print(f'wrote {os.path.relpath(OUT, REPO)}')
    print(f"{len(book['chapters'])} chapters, {total_paras} paragraphs, {total_words:,} words")
    print(f'{len(problems)} problem(s)')
    return 0


if __name__ == '__main__':
    sys.exit(main())
