//
//  ChantCatalogData.swift
//  Lumen Viae
//
//  GENERATED by Tools/Chants/generate.py from chants.json — edit the
//  selection there and regenerate; never by hand here.
//
//  Recordings and scores: Verbum Gloriae (verbumgloriae.es), under
//  their copyleft licence. The AAC files and recoloured scores bundled
//  here are adaptations and carry the same licence.
//

import Foundation

extension ChantCatalog {

    static let groups: [ChantGroup] = [
        ChantGroup(id: "ourLady", title: "Our Lady", note: "The antiphons of the year, her hymns and her litany"),
        ChantGroup(id: "rosary", title: "The Rosary and the Angelus", note: "The prayers of the beads, chanted as a Latin Rosary is sung"),
        ChantGroup(id: "sacrament", title: "The Blessed Sacrament", note: "For Mass, Benediction and a visit"),
        ChantGroup(id: "holyGhost", title: "The Holy Ghost", note: "Pentecost, and every work begun"),
        ChantGroup(id: "ourLord", title: "The Sacred Heart and the Holy Name", note: nil),
        ChantGroup(id: "praise", title: "Praise and Thanksgiving", note: nil),
        ChantGroup(id: "saints", title: "Angels and Saints", note: nil),
        ChantGroup(id: "advent", title: "Advent", note: nil),
        ChantGroup(id: "christmas", title: "Christmas", note: nil),
        ChantGroup(id: "lent", title: "Lent and Passiontide", note: nil),
        ChantGroup(id: "easter", title: "Easter", note: nil),
        ChantGroup(id: "departed", title: "The Faithful Departed", note: nil)
    ]

    static let all: [Chant] = [
        Chant(
            id: "salve_regina_simple",
            groupID: "ourLady",
            latinTitle: "Salve Regina",
            englishTitle: "Hail, Holy Queen",
            setting: "Simple tone",
            detail: "The evening antiphon from Trinity Sunday to Advent, and the Rosary's close",
            prayerIDs: ["hail_holy_queen"],
            duration: 185.0,
            score: [
                ChantScorePart(file: "chant-salve-regina-simple", caption: "Salve Regina simple", aspectRatio: 1.0797),
                ChantScorePart(file: "chant-vers-alt-ora-pro-nobis", caption: "Ora pro nobis", aspectRatio: 3.9357),
                ChantScorePart(file: "chant-or-omnipotens-sempiterne", caption: "Oremus. Omnipotens... qui gloriosae", aspectRatio: 1.5328)
            ],
            sourceURL: URL(string: "https://www.verbumgloriae.es/project/salve-regina-simple/")!
        ),
        Chant(
            id: "salve_regina_solemn",
            groupID: "ourLady",
            latinTitle: "Salve Regina",
            englishTitle: "Hail, Holy Queen",
            setting: "Solemn tone",
            detail: "The same antiphon in its older, richer melody",
            prayerIDs: ["hail_holy_queen"],
            duration: 250.1,
            score: [
                ChantScorePart(file: "chant-salve-regina-solemne", caption: "Salve Regina solemne", aspectRatio: 1.0723),
                ChantScorePart(file: "chant-vers-alt-ora-pro-nobis", caption: "Ora pro nobis", aspectRatio: 3.9357),
                ChantScorePart(file: "chant-or-omnipotens-sempiterne", caption: "Oremus. Omnipotens... qui gloriosae", aspectRatio: 1.5328)
            ],
            sourceURL: URL(string: "https://www.verbumgloriae.es/project/salve-regina-solemne/")!
        ),
        Chant(
            id: "alma_redemptoris",
            groupID: "ourLady",
            latinTitle: "Alma Redemptoris Mater",
            englishTitle: "Loving Mother of the Redeemer",
            setting: "Solemn tone",
            detail: "The evening antiphon from Advent to Candlemas",
            prayerIDs: ["alma_redemptoris"],
            duration: 210.0,
            score: [
                ChantScorePart(file: "chant-alma-redemptoris-mater-solemne", caption: "Alma Redemptoris Mater solemne", aspectRatio: 1.4196),
                ChantScorePart(file: "chant-vers-alt-angelus-domini", caption: "Angelus Domini", aspectRatio: 3.9357),
                ChantScorePart(file: "chant-or-gratiam-tuam", caption: "Oremus. Gratiam tuam quaesumus", aspectRatio: 1.9104),
                ChantScorePart(file: "chant-vers-alt-post-partum", caption: "Post partum", aspectRatio: 3.9357),
                ChantScorePart(file: "chant-or-deus-qui-salutis", caption: "Oremus. Deus qui salutis", aspectRatio: 1.8951)
            ],
            sourceURL: URL(string: "https://www.verbumgloriae.es/project/alma-redemptoris-mater-solemne/")!
        ),
        Chant(
            id: "ave_regina_simple",
            groupID: "ourLady",
            latinTitle: "Ave Regina Cælorum",
            englishTitle: "Hail, Queen of Heaven",
            setting: "Simple tone",
            detail: "The evening antiphon from Candlemas to Holy Week",
            prayerIDs: ["ave_regina_caelorum"],
            duration: 96.5,
            score: [
                ChantScorePart(file: "chant-ave-regina-caelorum-simple", caption: "Ave Regina caelorum simple", aspectRatio: 2.1857),
                ChantScorePart(file: "chant-vers-alt-dignare-me", caption: "Dignare me", aspectRatio: 3.9357),
                ChantScorePart(file: "chant-or-concede-misericors", caption: "Oremus. Concede misericors Deus", aspectRatio: 1.9585)
            ],
            sourceURL: URL(string: "https://www.verbumgloriae.es/project/ave-regina-caelorum-simple/")!
        ),
        Chant(
            id: "ave_regina_solemn",
            groupID: "ourLady",
            latinTitle: "Ave Regina Cælorum",
            englishTitle: "Hail, Queen of Heaven",
            setting: "Solemn tone",
            detail: "The same antiphon in its solemn melody",
            prayerIDs: ["ave_regina_caelorum"],
            duration: 138.0,
            score: [
                ChantScorePart(file: "chant-ave-regina-caelorum", caption: "Ave Regina caelorum solemne", aspectRatio: 1.6306),
                ChantScorePart(file: "chant-vers-alt-dignare-me", caption: "Dignare me", aspectRatio: 3.9357),
                ChantScorePart(file: "chant-or-concede-misericors", caption: "Oremus. Concede misericors Deus", aspectRatio: 1.9585)
            ],
            sourceURL: URL(string: "https://www.verbumgloriae.es/project/ave-regina-caelorum-solemne/")!
        ),
        Chant(
            id: "regina_caeli_simple",
            groupID: "ourLady",
            latinTitle: "Regina Cæli",
            englishTitle: "Queen of Heaven, Rejoice",
            setting: "Simple tone",
            detail: "The antiphon of Eastertide, sung in place of the Angelus",
            prayerIDs: ["regina_caeli"],
            duration: 91.0,
            score: [
                ChantScorePart(file: "chant-regina-caeli-simple", caption: "Regina caeli simple", aspectRatio: 3.6863),
                ChantScorePart(file: "chant-vers-alt-gaude-et-laetare", caption: "Gaude et laetare", aspectRatio: 3.9357),
                ChantScorePart(file: "chant-or-deus-qui-per-web", caption: "Oratio Deus qui per resurrectionem", aspectRatio: 1.8735)
            ],
            sourceURL: URL(string: "https://www.verbumgloriae.es/project/regina-caeli-simple/")!
        ),
        Chant(
            id: "regina_caeli_solemn",
            groupID: "ourLady",
            latinTitle: "Regina Cæli",
            englishTitle: "Queen of Heaven, Rejoice",
            setting: "Solemn tone",
            detail: "The same antiphon in its solemn melody",
            prayerIDs: ["regina_caeli"],
            duration: 144.0,
            score: [
                ChantScorePart(file: "chant-regina-caeli-solemne", caption: "Regina caeli solemne", aspectRatio: 1.8462),
                ChantScorePart(file: "chant-vers-alt-gaude-et-laetare", caption: "Gaude et laetare", aspectRatio: 3.9357),
                ChantScorePart(file: "chant-or-deus-qui-per-web", caption: "Oratio Deus qui per resurrectionem", aspectRatio: 1.8735)
            ],
            sourceURL: URL(string: "https://www.verbumgloriae.es/project/regina-caeli-solemne/")!
        ),
        Chant(
            id: "sub_tuum",
            groupID: "ourLady",
            latinTitle: "Sub Tuum Præsidium",
            englishTitle: "We Fly to Thy Patronage",
            setting: nil,
            detail: "The oldest prayer to Our Lady that survives",
            prayerIDs: ["sub_tuum"],
            duration: 104.1,
            score: [
                ChantScorePart(file: "chant-sub-tuum-praesidium", caption: "Sub tuum praesidium", aspectRatio: 2.3434),
                ChantScorePart(file: "chant-vers-alt-ora-pro-nobis", caption: "Ora pro nobis", aspectRatio: 3.9357),
                ChantScorePart(file: "chant-or-concede-nos-famulos", caption: "Oremus. Concede nos famulos tuos", aspectRatio: 1.9268)
            ],
            sourceURL: URL(string: "https://www.verbumgloriae.es/project/sub-tuum-praesidium/")!
        ),
        Chant(
            id: "ave_maris_stella",
            groupID: "ourLady",
            latinTitle: "Ave Maris Stella",
            englishTitle: "Hail, Star of the Sea",
            setting: nil,
            detail: "The Vespers hymn of her feasts and of her Saturdays",
            prayerIDs: ["ave_maris_stella"],
            duration: 132.0,
            score: [
                ChantScorePart(file: "chant-ave-maris-stella-off-bmv-in-sabb", caption: "Ave maris stella (Off. BMV in Sabb.)", aspectRatio: 0.8081)
            ],
            sourceURL: URL(string: "https://www.verbumgloriae.es/project/ave-maris-stella-off-bmv-in-sabb/")!
        ),
        Chant(
            id: "magnificat",
            groupID: "ourLady",
            latinTitle: "Magnificat",
            englishTitle: "The Canticle of Mary",
            setting: "With alleluia",
            detail: "Our Lady's own song, sung every evening at Vespers",
            prayerIDs: ["magnificat"],
            duration: 314.1,
            score: [
                ChantScorePart(file: "chant-magnificat-cum-alleluia", caption: "Magnificat cum Alleluia", aspectRatio: 0.2752)
            ],
            sourceURL: URL(string: "https://www.verbumgloriae.es/project/magnificat-cum-alleluia/")!
        ),
        Chant(
            id: "tota_pulchra",
            groupID: "ourLady",
            latinTitle: "Tota Pulchra Es",
            englishTitle: "Thou Art All Fair",
            setting: nil,
            detail: "In honour of the Immaculate Conception",
            prayerIDs: ["tota_pulchra"],
            duration: 108.0,
            score: [
                ChantScorePart(file: "chant-tota-pulchra-es-maria-web", caption: "Tota pulchra es Maria", aspectRatio: 1.1321)
            ],
            sourceURL: URL(string: "https://www.verbumgloriae.es/project/tota-pulchra-es-maria/")!
        ),
        Chant(
            id: "flos_carmeli",
            groupID: "ourLady",
            latinTitle: "Flos Carmeli",
            englishTitle: "Flower of Carmel",
            setting: nil,
            detail: "The sequence of Our Lady of Mount Carmel",
            prayerIDs: ["flos_carmeli"],
            duration: 168.0,
            score: [
                ChantScorePart(file: "chant-flos-carmeli-w", caption: "canto Flos Carmeli", aspectRatio: 0.7470)
            ],
            sourceURL: URL(string: "https://www.verbumgloriae.es/project/flos-carmeli/")!
        ),
        Chant(
            id: "stabat_mater",
            groupID: "ourLady",
            latinTitle: "Stabat Mater",
            englishTitle: "The Mother Stood",
            setting: "The sequence",
            detail: "The sequence of the Seven Sorrows",
            prayerIDs: ["stabat_mater"],
            duration: 330.0,
            score: [
                ChantScorePart(file: "chant-stabat-mater-seq", caption: "la secuencia Stabat Mater", aspectRatio: 0.3278)
            ],
            sourceURL: URL(string: "https://www.verbumgloriae.es/project/stabat-mater-sequentia/")!
        ),
        Chant(
            id: "litany_loreto",
            groupID: "ourLady",
            latinTitle: "Litaniæ Lauretanæ",
            englishTitle: "The Litany of Loreto",
            setting: nil,
            detail: "With the versicle and collect for each season",
            prayerIDs: ["litany_loreto"],
            duration: 784.1,
            score: [
                ChantScorePart(file: "chant-litaniae-lauretanae-1-kyrie", caption: "Kyrie eleison", aspectRatio: 3.6695),
                ChantScorePart(file: "chant-litaniae-lauretanae-2-pater", caption: "Pater de caelis", aspectRatio: 7.4264),
                ChantScorePart(file: "chant-litaniae-lauretanae-3-sancta-maria", caption: "Sancta Maria", aspectRatio: 7.4265),
                ChantScorePart(file: "chant-litaniae-lauretanae-4-mater-christi", caption: "Mater Christi", aspectRatio: 7.4265),
                ChantScorePart(file: "chant-litaniae-lauretanae-5-agnus", caption: "Agnus Dei", aspectRatio: 2.4138),
                ChantScorePart(file: "chant-vers-alt-ora-pro-nobis", caption: "Ora pro nobis", aspectRatio: 3.9357),
                ChantScorePart(file: "chant-or-concede-nos-famulos", caption: "Oremus. Concede nos famulos tuos", aspectRatio: 1.9268),
                ChantScorePart(file: "chant-vers-alt-angelus-domini", caption: "Angelus Domini", aspectRatio: 3.9357),
                ChantScorePart(file: "chant-litaniae-lauretanae-9-oratio-adventu-nativitatem", caption: "Oremus. Deus qui de beatae", aspectRatio: 1.8202),
                ChantScorePart(file: "chant-vers-alt-post-partum", caption: "Post partum", aspectRatio: 3.9357),
                ChantScorePart(file: "chant-or-deus-qui-salutis", caption: "Oremus. Deus qui salutis", aspectRatio: 1.8951),
                ChantScorePart(file: "chant-vers-alt-gaude-et-laetare", caption: "Gaude et laetare", aspectRatio: 3.9357)
            ],
            sourceURL: URL(string: "https://www.verbumgloriae.es/project/litaniae-lauretanae/")!
        ),
        Chant(
            id: "memorare",
            groupID: "ourLady",
            latinTitle: "Memorare",
            englishTitle: "Remember, O Most Gracious Virgin Mary",
            setting: nil,
            detail: "St Bernard's prayer, set to chant",
            prayerIDs: ["memorare"],
            duration: 128.3,
            score: [
                ChantScorePart(file: "chant-memorare-1", caption: "Memorare 1", aspectRatio: 1.0940)
            ],
            sourceURL: URL(string: "https://www.verbumgloriae.es/project/memorare-1/")!
        ),
        Chant(
            id: "ave_maria_antiphon",
            groupID: "ourLady",
            latinTitle: "Ave Maria",
            englishTitle: "Hail Mary, the antiphon",
            setting: "Antiphon",
            detail: "The Offertory of the last Sunday of Advent",
            prayerIDs: [],
            duration: 57.0,
            score: [
                ChantScorePart(file: "chant-ave-maria-antiphona", caption: "Ave Maria", aspectRatio: 2.1618)
            ],
            sourceURL: URL(string: "https://www.verbumgloriae.es/project/ave-maria-antiphona/")!
        ),
        Chant(
            id: "salve_mater",
            groupID: "ourLady",
            latinTitle: "Salve Mater Misericordiæ",
            englishTitle: "Hail, Mother of Mercy",
            setting: nil,
            detail: "A Marian hymn with a refrain for all to sing",
            prayerIDs: [],
            duration: 463.0,
            score: [
                ChantScorePart(file: "chant-salve-mater", caption: "canto Salve Mater", aspectRatio: 0.4119)
            ],
            sourceURL: URL(string: "https://www.verbumgloriae.es/project/salve-mater/")!
        ),
        Chant(
            id: "inviolata",
            groupID: "ourLady",
            latinTitle: "Inviolata",
            englishTitle: "Inviolate",
            setting: nil,
            detail: "A prose to the ever-Virgin",
            prayerIDs: [],
            duration: 90.0,
            score: [
                ChantScorePart(file: "chant-inviolata", caption: "la secuencia Inviolata", aspectRatio: 1.4473)
            ],
            sourceURL: URL(string: "https://www.verbumgloriae.es/project/inviolata/")!
        ),
        Chant(
            id: "o_gloriosa",
            groupID: "ourLady",
            latinTitle: "O Gloriosa Virginum",
            englishTitle: "O Glorious Virgin",
            setting: nil,
            detail: "The Lauds hymn of Our Lady's feasts",
            prayerIDs: [],
            duration: 119.1,
            score: [
                ChantScorePart(file: "chant-o-gloriosa-virginum", caption: "O gloriosa Virginum", aspectRatio: 1.1474)
            ],
            sourceURL: URL(string: "https://www.verbumgloriae.es/project/o-gloriosa-virginum/")!
        ),
        Chant(
            id: "in_nomine_patris",
            groupID: "rosary",
            latinTitle: "In Nomine Patris",
            englishTitle: "The Sign of the Cross",
            setting: nil,
            detail: "How a sung Rosary begins and ends",
            prayerIDs: ["sign_of_cross"],
            duration: 17.7,
            score: [
                ChantScorePart(file: "chant-in-nomine-patris", caption: "In nomine Patris", aspectRatio: 8.0662)
            ],
            sourceURL: URL(string: "https://www.verbumgloriae.es/cantos/santo-rosario/misterios-gozosos/")!
        ),
        Chant(
            id: "credo_in_deum",
            groupID: "rosary",
            latinTitle: "Credo in Deum",
            englishTitle: "The Apostles' Creed",
            setting: nil,
            detail: "On the crucifix",
            prayerIDs: ["apostles_creed"],
            duration: 175.1,
            score: [
                ChantScorePart(file: "chant-credo-in-deum", caption: "Credo in Deum", aspectRatio: 0.7762)
            ],
            sourceURL: URL(string: "https://www.verbumgloriae.es/cantos/santo-rosario/misterios-gozosos/")!
        ),
        Chant(
            id: "pater_noster",
            groupID: "rosary",
            latinTitle: "Pater Noster",
            englishTitle: "Our Father",
            setting: nil,
            detail: "On each large bead",
            prayerIDs: ["our_father"],
            duration: 56.0,
            score: [
                ChantScorePart(file: "chant-pater-noster", caption: "Pater noster", aspectRatio: 1.4872)
            ],
            sourceURL: URL(string: "https://www.verbumgloriae.es/cantos/santo-rosario/misterios-gozosos/")!
        ),
        Chant(
            id: "ave_maria",
            groupID: "rosary",
            latinTitle: "Ave Maria",
            englishTitle: "Hail Mary",
            setting: nil,
            detail: "On each small bead, as the Rosary is sung",
            prayerIDs: ["hail_mary"],
            duration: 39.0,
            score: [
                ChantScorePart(file: "chant-ave-maria", caption: "Ave Maria", aspectRatio: 2.5200)
            ],
            sourceURL: URL(string: "https://www.verbumgloriae.es/cantos/santo-rosario/misterios-gozosos/")!
        ),
        Chant(
            id: "gloria_patri",
            groupID: "rosary",
            latinTitle: "Gloria Patri",
            englishTitle: "Glory Be",
            setting: nil,
            detail: "At the close of every decade",
            prayerIDs: ["glory_be"],
            duration: 32.0,
            score: [
                ChantScorePart(file: "chant-gloria-patri-iii-ant", caption: "Gloria Patri", aspectRatio: 3.7584)
            ],
            sourceURL: URL(string: "https://www.verbumgloriae.es/cantos/santo-rosario/misterios-gozosos/")!
        ),
        Chant(
            id: "o_mi_jesu",
            groupID: "rosary",
            latinTitle: "O mi Jesu",
            englishTitle: "The Fatima Prayer",
            setting: nil,
            detail: "After the Glory Be, with a second aspiration to Our Lady",
            prayerIDs: ["fatima_prayer"],
            duration: 34.5,
            score: [
                ChantScorePart(file: "chant-o-mi-jesu", caption: "First aspiration", aspectRatio: 3.7498),
                ChantScorePart(file: "chant-o-maria", caption: "Second aspiration", aspectRatio: 9.0027)
            ],
            sourceURL: URL(string: "https://www.verbumgloriae.es/cantos/santo-rosario/misterios-gozosos/")!
        ),
        Chant(
            id: "angelus",
            groupID: "rosary",
            latinTitle: "Angelus Domini",
            englishTitle: "The Angelus",
            setting: nil,
            detail: "At six, at noon and at six, with its collect",
            prayerIDs: ["angelus"],
            duration: 234.9,
            score: [
                ChantScorePart(file: "chant-angelus-domini", caption: "Angelus Domini", aspectRatio: 3.8909),
                ChantScorePart(file: "chant-ave-maria", caption: "Ave Maria", aspectRatio: 2.5200),
                ChantScorePart(file: "chant-ecce-ancilla-domini", caption: "Ecce ancilla Domini", aspectRatio: 7.7402),
                ChantScorePart(file: "chant-et-verbum-caro", caption: "Et Verbum", aspectRatio: 7.8438),
                ChantScorePart(file: "chant-vers-alt-ora-pro-nobis", caption: "Ora pro nobis", aspectRatio: 3.9357),
                ChantScorePart(file: "chant-or-gratiam-tuam", caption: "Oremus. Gratiam tuam quaesumus", aspectRatio: 1.9104),
                ChantScorePart(file: "chant-gloria-patri-ii-mon", caption: "Gloria Patri", aspectRatio: 3.8498)
            ],
            sourceURL: URL(string: "https://www.verbumgloriae.es/cantos/angelus/")!
        ),
        Chant(
            id: "adoro_te",
            groupID: "sacrament",
            latinTitle: "Adoro Te Devote",
            englishTitle: "I Adore Thee Devoutly",
            setting: nil,
            detail: "St Thomas Aquinas's hymn to the hidden God",
            prayerIDs: ["adoro_te"],
            duration: 264.0,
            score: [
                ChantScorePart(file: "chant-adoro-te-devote", caption: "Adoro te devote", aspectRatio: 0.4441)
            ],
            sourceURL: URL(string: "https://www.verbumgloriae.es/project/adoro-te-devote/")!
        ),
        Chant(
            id: "ave_verum",
            groupID: "sacrament",
            latinTitle: "Ave Verum Corpus",
            englishTitle: "Hail, True Body",
            setting: nil,
            detail: "Sung at the Elevation and at Benediction",
            prayerIDs: ["ave_verum"],
            duration: 87.0,
            score: [
                ChantScorePart(file: "chant-ave-verum-corpus", caption: "Ave verum Corpus", aspectRatio: 1.7547)
            ],
            sourceURL: URL(string: "https://www.verbumgloriae.es/project/ave-verum-corpus/")!
        ),
        Chant(
            id: "o_salutaris",
            groupID: "sacrament",
            latinTitle: "O Salutaris Hostia",
            englishTitle: "O Saving Victim",
            setting: nil,
            detail: "Sung as the Host is set in the monstrance",
            prayerIDs: ["o_salutaris"],
            duration: 66.0,
            score: [
                ChantScorePart(file: "chant-o-salutaris-hostia-i", caption: "O salutaris Hostia I", aspectRatio: 2.3522)
            ],
            sourceURL: URL(string: "https://www.verbumgloriae.es/project/o-salutaris-hostia-i/")!
        ),
        Chant(
            id: "tantum_ergo",
            groupID: "sacrament",
            latinTitle: "Tantum Ergo",
            englishTitle: "Down in Adoration Falling",
            setting: nil,
            detail: "Sung before the blessing at Benediction",
            prayerIDs: ["tantum_ergo"],
            duration: 137.4,
            score: [
                ChantScorePart(file: "chant-tantum-ergo-i", caption: "Tantum ergo I", aspectRatio: 1.3729),
                ChantScorePart(file: "chant-vers-panem-de-caelo", caption: "Panem de caelo", aspectRatio: 3.9357),
                ChantScorePart(file: "chant-or-deus-qui-nobis", caption: "Oremus. Deus qui nobis", aspectRatio: 1.8202)
            ],
            sourceURL: URL(string: "https://www.verbumgloriae.es/project/tantum-ergo-i/")!
        ),
        Chant(
            id: "o_sacrum_convivium",
            groupID: "sacrament",
            latinTitle: "O Sacrum Convivium",
            englishTitle: "O Sacred Banquet",
            setting: nil,
            detail: "The Magnificat antiphon of Corpus Christi",
            prayerIDs: ["o_sacrum_convivium"],
            duration: 118.0,
            score: [
                ChantScorePart(file: "chant-o-sacrum-convivium", caption: "la antífona O sacrum convivium", aspectRatio: 1.6858)
            ],
            sourceURL: URL(string: "https://www.verbumgloriae.es/project/o-sacrum-convivium/")!
        ),
        Chant(
            id: "divine_praises",
            groupID: "sacrament",
            latinTitle: "Laudes Divinæ",
            englishTitle: "The Divine Praises",
            setting: nil,
            detail: "Said or sung after the blessing at Benediction",
            prayerIDs: ["divine_praises"],
            duration: 127.1,
            score: [
                ChantScorePart(file: "chant-laudes-divinae", caption: "Laudes Divinae", aspectRatio: 0.7377)
            ],
            sourceURL: URL(string: "https://www.verbumgloriae.es/project/laudes-divinae/")!
        ),
        Chant(
            id: "anima_christi",
            groupID: "sacrament",
            latinTitle: "Anima Christi",
            englishTitle: "Soul of Christ",
            setting: nil,
            detail: "A thanksgiving after Communion",
            prayerIDs: ["anima_christi"],
            duration: 90.0,
            score: [
                ChantScorePart(file: "chant-anima-christi-i", caption: "Anima Christi I", aspectRatio: 1.1418)
            ],
            sourceURL: URL(string: "https://www.verbumgloriae.es/project/anima-christi-i/")!
        ),
        Chant(
            id: "panis_angelicus",
            groupID: "sacrament",
            latinTitle: "Panis Angelicus",
            englishTitle: "Bread of Angels",
            setting: nil,
            detail: "From St Thomas's hymn for the Matins of Corpus Christi",
            prayerIDs: [],
            duration: 87.0,
            score: [
                ChantScorePart(file: "chant-panis-angelicus", caption: "himno Panis angelicus I", aspectRatio: 1.3132)
            ],
            sourceURL: URL(string: "https://www.verbumgloriae.es/project/panis-angelicus-1/")!
        ),
        Chant(
            id: "lauda_sion",
            groupID: "sacrament",
            latinTitle: "Lauda Sion",
            englishTitle: "Praise, O Sion",
            setting: nil,
            detail: "The sequence of Corpus Christi",
            prayerIDs: [],
            duration: 438.0,
            score: [
                ChantScorePart(file: "chant-lauda-sion-salvatorem", caption: "la secuencia Lauda Sion Salvatorem", aspectRatio: 0.2300)
            ],
            sourceURL: URL(string: "https://www.verbumgloriae.es/project/lauda-sion-salvatorem/")!
        ),
        Chant(
            id: "adoremus",
            groupID: "sacrament",
            latinTitle: "Adoremus in Æternum",
            englishTitle: "Let Us Adore For Ever",
            setting: nil,
            detail: "Sung at the close of Benediction",
            prayerIDs: [],
            duration: 101.0,
            score: [
                ChantScorePart(file: "chant-adoremus-in-aeternum-1", caption: "canto Adoremus in aeternum 1", aspectRatio: 1.1634)
            ],
            sourceURL: URL(string: "https://www.verbumgloriae.es/project/adoremus-in-aeternum-1/")!
        ),
        Chant(
            id: "ecce_panis",
            groupID: "sacrament",
            latinTitle: "Ecce Panis Angelorum",
            englishTitle: "Behold the Bread of Angels",
            setting: nil,
            detail: "The last verses of the Lauda Sion",
            prayerIDs: [],
            duration: 101.0,
            score: [
                ChantScorePart(file: "chant-ecce-panis-angelorum", caption: "la secuencia Ecce panis Angelorum", aspectRatio: 1.1051)
            ],
            sourceURL: URL(string: "https://www.verbumgloriae.es/project/ecce-panis-angelorum/")!
        ),
        Chant(
            id: "ubi_caritas",
            groupID: "sacrament",
            latinTitle: "Ubi Caritas",
            englishTitle: "Where Charity and Love Are",
            setting: nil,
            detail: "Sung at the washing of feet on Holy Thursday",
            prayerIDs: [],
            duration: 152.0,
            score: [
                ChantScorePart(file: "chant-ubi-caritas", caption: "canto Ubi caritas", aspectRatio: 0.7458)
            ],
            sourceURL: URL(string: "https://www.verbumgloriae.es/project/ubi-caritas/")!
        ),
        Chant(
            id: "veni_creator",
            groupID: "holyGhost",
            latinTitle: "Veni Creator Spiritus",
            englishTitle: "Come, Creator Spirit",
            setting: nil,
            detail: "The hymn of Pentecost, with its versicle and collect",
            prayerIDs: ["veni_creator"],
            duration: 248.1,
            score: [
                ChantScorePart(file: "chant-veni-creator-spiritus", caption: "Veni Creator Spiritus", aspectRatio: 0.6219),
                ChantScorePart(file: "chant-vers-emitte-spiritum", caption: "Emitte Spiritum tuum", aspectRatio: 3.9167),
                ChantScorePart(file: "chant-or-deus-qui-corda", caption: "Oremus. Deus qui corda", aspectRatio: 2.4607)
            ],
            sourceURL: URL(string: "https://www.verbumgloriae.es/project/veni-creator-spiritus/")!
        ),
        Chant(
            id: "veni_sancte_spiritus",
            groupID: "holyGhost",
            latinTitle: "Veni Sancte Spiritus",
            englishTitle: "Come, Holy Spirit",
            setting: "The sequence",
            detail: "The Golden Sequence of Pentecost",
            prayerIDs: ["veni_sancte_spiritus"],
            duration: 157.1,
            score: [
                ChantScorePart(file: "chant-veni-sancte-spiritus-web", caption: "Veni Sancte Spiritus", aspectRatio: 0.6576)
            ],
            sourceURL: URL(string: "https://www.verbumgloriae.es/project/veni-sancte-spiritus/")!
        ),
        Chant(
            id: "veni_sancte_reple",
            groupID: "holyGhost",
            latinTitle: "Veni Sancte Spiritus, Reple",
            englishTitle: "Come, Holy Ghost",
            setting: "Antiphon",
            detail: "Before prayer, study or any work begun",
            prayerIDs: ["come_holy_ghost"],
            duration: 88.1,
            score: [
                ChantScorePart(file: "chant-veni-sancte-spiritus-reple", caption: "Veni Sancte Spiritus reple", aspectRatio: 2.3688),
                ChantScorePart(file: "chant-vers-emitte-spiritum", caption: "Emitte Spiritum tuum", aspectRatio: 3.9167),
                ChantScorePart(file: "chant-or-deus-qui-corda", caption: "Oremus. Deus qui corda", aspectRatio: 2.4607)
            ],
            sourceURL: URL(string: "https://www.verbumgloriae.es/project/veni-sancte-spiritus-reple/")!
        ),
        Chant(
            id: "litany_sacred_heart",
            groupID: "ourLord",
            latinTitle: "Litaniæ Sacratissimi Cordis",
            englishTitle: "The Litany of the Sacred Heart",
            setting: nil,
            detail: "For First Fridays and the month of June",
            prayerIDs: ["litany_sacred_heart"],
            duration: 698.1,
            score: [
                ChantScorePart(file: "chant-litaniae-ss-cordis-jesu-1-kyrie", caption: "Kyrie eleison", aspectRatio: 3.5979),
                ChantScorePart(file: "chant-litaniae-ss-cordis-jesu-2-pater", caption: "Pater de caelis", aspectRatio: 7.4264),
                ChantScorePart(file: "chant-litaniae-ss-cordis-jesu-3-cor-jesu", caption: "Cor Jesu Filii Patris aeterni", aspectRatio: 7.4264),
                ChantScorePart(file: "chant-litaniae-ss-cordis-jesu-4-agnus-dei", caption: "Agnus Dei", aspectRatio: 2.2380),
                ChantScorePart(file: "chant-litaniae-ss-cordis-jesu-5-vers-jesu-mitis", caption: "Jesu mitis", aspectRatio: 3.9357),
                ChantScorePart(file: "chant-litaniae-ss-cordis-jesu-6-or-omn-respice", caption: "Oremus. Omnipotens... respice in Cor", aspectRatio: 1.4443)
            ],
            sourceURL: URL(string: "https://www.verbumgloriae.es/project/litaniae-sacratissimi-cordis-jesu/")!
        ),
        Chant(
            id: "litany_holy_name",
            groupID: "ourLord",
            latinTitle: "Litaniæ Sanctissimi Nominis",
            englishTitle: "The Litany of the Holy Name",
            setting: nil,
            detail: "Approved for the whole Church in 1862",
            prayerIDs: ["litany_holy_name"],
            duration: 876.0,
            score: [
                ChantScorePart(file: "chant-litaniae-sanctissimi-nominis-jesu-0", caption: "los Kyries de las Litaniae Santissimi Nominis Jesu", aspectRatio: 3.8323),
                ChantScorePart(file: "chant-litaniae-sanctissimi-nominis-jesu-1", caption: "Pater de caelis de las Litaniae Santissimi Nominis Jesu", aspectRatio: 8.0851),
                ChantScorePart(file: "chant-litaniae-sanctissimi-nominis-jesu-2", caption: "Jesu Fili Dei vivi de las Litaniae Santissimi Nominis Jesu", aspectRatio: 8.0851),
                ChantScorePart(file: "chant-litaniae-sanctissimi-nominis-jesu-3-alt", caption: "Propitius esto de las Litaniae Sanctissimi Nominis Jesu", aspectRatio: 4.5157),
                ChantScorePart(file: "chant-litaniae-sanctissimi-nominis-jesu-4", caption: "Agnus Dei de las Litaniae Sanctissimi Nominis Jesu", aspectRatio: 1.8174),
                ChantScorePart(file: "chant-litaniae-sanctissimi-nominis-jesu-5", caption: "Collect", aspectRatio: 0.7909)
            ],
            sourceURL: URL(string: "https://www.verbumgloriae.es/project/litaniae-sanctissimi-nominis-jesu/")!
        ),
        Chant(
            id: "jesu_dulcis_memoria",
            groupID: "ourLord",
            latinTitle: "Jesu Dulcis Memoria",
            englishTitle: "Jesus, the Very Thought of Thee",
            setting: nil,
            detail: "The hymn of the Holy Name",
            prayerIDs: [],
            duration: 116.1,
            score: [
                ChantScorePart(file: "chant-jesu-dulcis-memoria", caption: "himno Jesu dulcis memoria", aspectRatio: 0.8348)
            ],
            sourceURL: URL(string: "https://www.verbumgloriae.es/project/jesu-dulcis-memoria/")!
        ),
        Chant(
            id: "cor_jesu",
            groupID: "ourLord",
            latinTitle: "Cor Jesu Sacratissimum",
            englishTitle: "Most Sacred Heart of Jesus",
            setting: nil,
            detail: "An invocation of the Sacred Heart",
            prayerIDs: [],
            duration: 38.1,
            score: [
                ChantScorePart(file: "chant-cor-jesu-sacratissimum-i", caption: "Cor Jesu sacratissimum I", aspectRatio: 7.1647)
            ],
            sourceURL: URL(string: "https://www.verbumgloriae.es/project/cor-jesu-sacratissimum-i/")!
        ),
        Chant(
            id: "te_deum",
            groupID: "praise",
            latinTitle: "Te Deum",
            englishTitle: "We Praise Thee, O God",
            setting: "Solemn tone",
            detail: "The Church's great hymn of thanksgiving, with its versicles and collect",
            prayerIDs: ["te_deum"],
            duration: 451.1,
            score: [
                ChantScorePart(file: "chant-te-deum-solemne", caption: "Te Deum", aspectRatio: 0.3275),
                ChantScorePart(file: "chant-versos-del-te-deum", caption: "Versicles and responses", aspectRatio: 1.0171),
                ChantScorePart(file: "chant-oracion-del-te-deum", caption: "Collect", aspectRatio: 1.4494)
            ],
            sourceURL: URL(string: "https://www.verbumgloriae.es/project/te-deum-solemne/")!
        ),
        Chant(
            id: "christus_vincit",
            groupID: "praise",
            latinTitle: "Christus Vincit",
            englishTitle: "Christ Conquers",
            setting: "Simple tone",
            detail: "The acclamations of Christ the King",
            prayerIDs: [],
            duration: 128.1,
            score: [
                ChantScorePart(file: "chant-christus-vincit-simple", caption: "Christus vincit simple", aspectRatio: 2.2434)
            ],
            sourceURL: URL(string: "https://www.verbumgloriae.es/project/christus-vincit-simple/")!
        ),
        Chant(
            id: "sancte_michael",
            groupID: "saints",
            latinTitle: "Sancte Michael Archangele",
            englishTitle: "St Michael the Archangel",
            setting: nil,
            detail: "Pope Leo XIII's prayer, set to chant",
            prayerIDs: ["st_michael_prayer"],
            duration: 90.0,
            score: [
                ChantScorePart(file: "chant-sancte-michael-archangele", caption: "Sancte Michael archangele", aspectRatio: 1.3042)
            ],
            sourceURL: URL(string: "https://www.verbumgloriae.es/project/sancte-michael-archangele/")!
        ),
        Chant(
            id: "litany_st_joseph",
            groupID: "saints",
            latinTitle: "Litaniæ Sancti Joseph",
            englishTitle: "The Litany of St Joseph",
            setting: nil,
            detail: "For Wednesdays and the month of March",
            prayerIDs: ["litany_st_joseph"],
            duration: 470.1,
            score: [
                ChantScorePart(file: "chant-litaniae-s-joseph-1-kyrie", caption: "Kyrie eleison", aspectRatio: 3.6680),
                ChantScorePart(file: "chant-litaniae-s-joseph-2-pater", caption: "Pater de caelis", aspectRatio: 7.4265),
                ChantScorePart(file: "chant-litaniae-s-joseph-3-1-sancta-maria", caption: "Sancta Maria", aspectRatio: 7.4264),
                ChantScorePart(file: "chant-litaniae-s-joseph-4-agnus-dei", caption: "Agnus Dei", aspectRatio: 2.4138),
                ChantScorePart(file: "chant-vers-alt-constituit-eum", caption: "Constituit eum", aspectRatio: 3.9357),
                ChantScorePart(file: "chant-litaniae-s-joseph-6-oratio", caption: "Oremus. Deus qui ineffabili", aspectRatio: 1.8202)
            ],
            sourceURL: URL(string: "https://www.verbumgloriae.es/project/litaniae-sancti-joseph/")!
        ),
        Chant(
            id: "te_joseph",
            groupID: "saints",
            latinTitle: "Te Joseph Celebrent",
            englishTitle: "Let Heaven Sing Thee, Joseph",
            setting: nil,
            detail: "The Vespers hymn of St Joseph",
            prayerIDs: [],
            duration: 197.1,
            score: [
                ChantScorePart(file: "chant-te-joseph-celebrent", caption: "Te Joseph celebrent", aspectRatio: 0.5867)
            ],
            sourceURL: URL(string: "https://www.verbumgloriae.es/project/te-joseph-celebrent/")!
        ),
        Chant(
            id: "litany_saints",
            groupID: "saints",
            latinTitle: "Litaniæ Sanctorum",
            englishTitle: "The Litany of the Saints",
            setting: nil,
            detail: "The oldest litany of the Church",
            prayerIDs: [],
            duration: 1072.1,
            score: [
                ChantScorePart(file: "chant-litaniae-sanctorum-1-kyrie-eleison", caption: "los Kyries de las Letanías de los Santos", aspectRatio: 3.9167),
                ChantScorePart(file: "chant-litaniae-sanctorum-2-pater-de-caelis", caption: "Pater de caelis de las Letanías de los Santos", aspectRatio: 7.8361),
                ChantScorePart(file: "chant-litaniae-sanctorum-3-propitius-esto", caption: "Propitius esto de las Letanías de los Santos", aspectRatio: 4.6023),
                ChantScorePart(file: "chant-litaniae-sanctorum-4-peccatores", caption: "Peccatores de las Letanías de los Santos", aspectRatio: 7.8361),
                ChantScorePart(file: "chant-litaniae-sanctorum-5-agnus-dei-kyrie", caption: "Agnus Dei y los Kyries de las Letanías de los Santos", aspectRatio: 1.4128)
            ],
            sourceURL: URL(string: "https://www.verbumgloriae.es/project/litaniae-sanctorum/")!
        ),
        Chant(
            id: "rorate_caeli",
            groupID: "advent",
            latinTitle: "Rorate Cæli",
            englishTitle: "Drop Down Dew, Ye Heavens",
            setting: nil,
            detail: "The prayer of Advent's waiting",
            prayerIDs: [],
            duration: 288.0,
            score: [
                ChantScorePart(file: "chant-rorate-caeli", caption: "Rorate caeli", aspectRatio: 0.4364)
            ],
            sourceURL: URL(string: "https://www.verbumgloriae.es/project/rorate-caeli/")!
        ),
        Chant(
            id: "creator_alme",
            groupID: "advent",
            latinTitle: "Creator Alme Siderum",
            englishTitle: "Creator of the Stars of Night",
            setting: nil,
            detail: "The Vespers hymn of Advent",
            prayerIDs: [],
            duration: 125.1,
            score: [
                ChantScorePart(file: "chant-creator-alme-siderum", caption: "himno Creator alme siderum", aspectRatio: 0.7705)
            ],
            sourceURL: URL(string: "https://www.verbumgloriae.es/project/creator-alme-siderum/")!
        ),
        Chant(
            id: "veni_emmanuel",
            groupID: "advent",
            latinTitle: "Veni, Veni, Emmanuel",
            englishTitle: "O Come, O Come, Emmanuel",
            setting: nil,
            detail: "The O Antiphons made a hymn",
            prayerIDs: [],
            duration: 272.1,
            score: [
                ChantScorePart(file: "chant-veni-veni-emmanuel-webfix", caption: "Veni veni Emmanuel, corregida la errata de la versión previa", aspectRatio: 0.4292)
            ],
            sourceURL: URL(string: "https://www.verbumgloriae.es/project/veni-veni-emmanuel/")!
        ),
        Chant(
            id: "puer_natus",
            groupID: "christmas",
            latinTitle: "Puer Natus in Bethlehem",
            englishTitle: "A Child Is Born in Bethlehem",
            setting: nil,
            detail: "A Christmas carol of the Middle Ages",
            prayerIDs: [],
            duration: 444.0,
            score: [
                ChantScorePart(file: "chant-puer-natus-in-bethlehem-web", caption: "Puer natus in Bethlehem", aspectRatio: 0.2416)
            ],
            sourceURL: URL(string: "https://www.verbumgloriae.es/project/puer-natus-in-bethlehem/")!
        ),
        Chant(
            id: "adeste_fideles",
            groupID: "christmas",
            latinTitle: "Adeste Fideles",
            englishTitle: "O Come, All Ye Faithful",
            setting: nil,
            detail: "The Christmas hymn in its Latin",
            prayerIDs: [],
            duration: 315.0,
            score: [
                ChantScorePart(file: "chant-adeste-fideles", caption: "himno Adeste fideles", aspectRatio: 0.5907)
            ],
            sourceURL: URL(string: "https://www.verbumgloriae.es/project/adeste-fideles/")!
        ),
        Chant(
            id: "jesu_redemptor",
            groupID: "christmas",
            latinTitle: "Jesu Redemptor Omnium",
            englishTitle: "Jesus, Redeemer of All",
            setting: nil,
            detail: "The Vespers hymn of Christmas",
            prayerIDs: [],
            duration: 203.1,
            score: [
                ChantScorePart(file: "chant-jesu-redemptor-omnium", caption: "himno Jesu Redemptor omnium", aspectRatio: 0.5821)
            ],
            sourceURL: URL(string: "https://www.verbumgloriae.es/project/jesu-redemptor-omnium/")!
        ),
        Chant(
            id: "attende_domine",
            groupID: "lent",
            latinTitle: "Attende Domine",
            englishTitle: "Hear Us, O Lord",
            setting: nil,
            detail: "Lent's plea for mercy",
            prayerIDs: [],
            duration: 212.1,
            score: [
                ChantScorePart(file: "chant-attende-domine-web-1", caption: "Attende Domine", aspectRatio: 0.5725)
            ],
            sourceURL: URL(string: "https://www.verbumgloriae.es/project/attende-domine/")!
        ),
        Chant(
            id: "parce_domine",
            groupID: "lent",
            latinTitle: "Parce Domine",
            englishTitle: "Spare, O Lord",
            setting: nil,
            detail: "From the prophet Joel, sung in Lent",
            prayerIDs: [],
            duration: 243.0,
            score: [
                ChantScorePart(file: "chant-parce-domine-web-1", caption: "Parce Domine", aspectRatio: 0.5675)
            ],
            sourceURL: URL(string: "https://www.verbumgloriae.es/project/parce-domine/")!
        ),
        Chant(
            id: "miserere",
            groupID: "lent",
            latinTitle: "Miserere Mei, Deus",
            englishTitle: "Psalm 50 · Have Mercy on Me",
            setting: nil,
            detail: "David's psalm of repentance",
            prayerIDs: ["miserere"],
            duration: 320.1,
            score: [
                ChantScorePart(file: "chant-miserere-mei-deus", caption: "Miserere mei Deus", aspectRatio: 0.2883)
            ],
            sourceURL: URL(string: "https://www.verbumgloriae.es/project/miserere-mei-deus/")!
        ),
        Chant(
            id: "vexilla_regis",
            groupID: "lent",
            latinTitle: "Vexilla Regis",
            englishTitle: "The Banners of the King",
            setting: nil,
            detail: "The Vespers hymn of Passiontide",
            prayerIDs: [],
            duration: 205.1,
            score: [
                ChantScorePart(file: "chant-vexilla-regis-prodeunt", caption: "Vexilla Regis prodeunt", aspectRatio: 0.5869)
            ],
            sourceURL: URL(string: "https://www.verbumgloriae.es/project/vexilla-regis-prodeunt/")!
        ),
        Chant(
            id: "victimae_paschali",
            groupID: "easter",
            latinTitle: "Victimæ Paschali Laudes",
            englishTitle: "Praises to the Paschal Victim",
            setting: nil,
            detail: "The sequence of Easter Sunday",
            prayerIDs: [],
            duration: 114.0,
            score: [
                ChantScorePart(file: "chant-victimae-paschali-laudes", caption: "Victimae paschali laudes", aspectRatio: 0.8993)
            ],
            sourceURL: URL(string: "https://www.verbumgloriae.es/project/victimae-paschali-laudes/")!
        ),
        Chant(
            id: "o_filii",
            groupID: "easter",
            latinTitle: "O Filii et Filiæ",
            englishTitle: "O Sons and Daughters",
            setting: nil,
            detail: "An Easter carol of the Resurrection",
            prayerIDs: [],
            duration: 390.0,
            score: [
                ChantScorePart(file: "chant-o-filii-et-filiae-web-1", caption: "O filii et filiae", aspectRatio: 0.2594)
            ],
            sourceURL: URL(string: "https://www.verbumgloriae.es/project/o-filii-et-filiae/")!
        ),
        Chant(
            id: "dies_irae",
            groupID: "departed",
            latinTitle: "Dies Iræ",
            englishTitle: "Day of Wrath",
            setting: nil,
            detail: "The sequence of the Requiem Mass",
            prayerIDs: [],
            duration: 384.0,
            score: [
                ChantScorePart(file: "chant-dies-irae", caption: "Dies irae", aspectRatio: 0.2827)
            ],
            sourceURL: URL(string: "https://www.verbumgloriae.es/project/dies-irae/")!
        )
    ]
}
