//
//  ScripturalRosaryData.swift
//  Lumen Viae
//
//  GENERATED by Tools/ScripturalRosary/generate.py — edit the
//  curated references there and regenerate; never by hand here.
//
//  A scripture verse for every bead: the Scriptural Rosary walks
//  each mystery through the sacred page itself, one verse per
//  Hail Mary. Text is the Douay-Rheims (public domain, CC0 via
//  thedouayrheims.com), bundled so prayer never needs a signal.
//

import Foundation

// MARK: - ScripturalVerse

/// One verse of Scripture prayed on one bead.
struct ScripturalVerse: Hashable {
    /// Douay-Rheims citation, e.g. "Luke 1:28"
    let reference: String
    /// The verse itself, Douay-Rheims text
    let text: String
}

// MARK: - ScripturalRosaryData

/// Verse-per-bead sets keyed "<category>_<order>", the same key
/// MysteryData uses for its fruits. Ten verses per mystery; seven
/// per sorrow of the Seven Sorrows chaplet.
enum ScripturalRosaryData {

    /// Verses for one mystery, in bead order — nil when no set
    /// has been curated for the key, and the prayer screen simply
    /// stays as it was.
    static func verses(category: String, order: Int) -> [ScripturalVerse]? {
        all["\(category)_\(order)"]
    }

    static let all: [String: [ScripturalVerse]] = [
        "joyful_1": [
            ScripturalVerse(reference: "Luke 1:26", text: "And in the sixth month, the Angel Gabriel was sent of God into a city of Galilee, called Nazareth,"),
            ScripturalVerse(reference: "Luke 1:27", text: "To a virgin despoused to a man whose name was Joseph, of the house of David; and the virgin's name was Mary."),
            ScripturalVerse(reference: "Luke 1:28", text: "And the Angel being entered in, said unto her: Hail full of grace, our Lord is with thee: blessed art thou among women."),
            ScripturalVerse(reference: "Luke 1:30", text: "And the Angel said to her: Fear not Mary, for thou hast found grace with God."),
            ScripturalVerse(reference: "Luke 1:31", text: "Behold thou shalt conceive in thy womb, and shalt bear a Son; and thou shalt call his name Jesus."),
            ScripturalVerse(reference: "Luke 1:32", text: "He shall be great, and shall be called the Son of the most High, and our Lord God shall give him the seat of David his father:"),
            ScripturalVerse(reference: "Luke 1:34", text: "And Mary said to the Angel: How shall this be done, because I know not man?"),
            ScripturalVerse(reference: "Luke 1:35", text: "And the Angel answering, said to her: The Holy Ghost shall come upon thee, and the power of the most High shall overshadow thee. And therefore also that which of thee shall be born Holy, shall be called the Son of God."),
            ScripturalVerse(reference: "Luke 1:37", text: "Because there shall not be impossible with God any word."),
            ScripturalVerse(reference: "Luke 1:38", text: "And Mary said, Behold the handmaid of our Lord, be it done to me according to thy word. And the Angel departed from her."),
        ],
        "joyful_2": [
            ScripturalVerse(reference: "Luke 1:39", text: "And Mary rising up in those days, went unto the hill country with speed into a city of Juda."),
            ScripturalVerse(reference: "Luke 1:41", text: "And it came to pass; as Elizabeth heard the salutation of Mary, the infant did leap in her womb. And Elizabeth was replenished with the Holy Ghost:"),
            ScripturalVerse(reference: "Luke 1:42", text: "And she cried out with a loud voice, and said, Blessed art thou among women, and blessed is the fruit of thy womb."),
            ScripturalVerse(reference: "Luke 1:43", text: "And whence is this to me, that the mother of my Lord doth come to me?"),
            ScripturalVerse(reference: "Luke 1:44", text: "For behold as the voice of thy salutation sounded in mine ears, the infant in my womb did leap for joy."),
            ScripturalVerse(reference: "Luke 1:45", text: "And Blessed is she that believed because those things shall be accomplished that were spoken to her by our Lord."),
            ScripturalVerse(reference: "Luke 1:46", text: "And Mary said: MY Soul doth magnify our Lord:"),
            ScripturalVerse(reference: "Luke 1:47", text: "And my spirit hath rejoiced in God my Saviour."),
            ScripturalVerse(reference: "Luke 1:48", text: "Because he hath regarded the humility of his handmaid; for behold from hence forth all generations shall call me blessed."),
            ScripturalVerse(reference: "Luke 1:49", text: "Because he that is mighty hath done great things to me: and holy is his name."),
        ],
        "joyful_3": [
            ScripturalVerse(reference: "Luke 2:1", text: "And it came to pass, in those days there came forth an Edict from Cæsar Augustus that the whole world should be enrolled."),
            ScripturalVerse(reference: "Luke 2:4", text: "And Joseph also went up from Galilee out of the city of Nazareth into Jewry, to the city of David that is called Beth-lehem: for because he was of the house and family of David,"),
            ScripturalVerse(reference: "Luke 2:6", text: "And it came to pass, when they were there, her days were fully come that she should be delivered."),
            ScripturalVerse(reference: "Luke 2:7", text: "And she brought forth her first begotten son, and swaddled him in cloths, and laid him down in a manger; because there was not place for them in the inn."),
            ScripturalVerse(reference: "Luke 2:8", text: "And there were in the same country shepherds watching, and keeping the night watches over their flock."),
            ScripturalVerse(reference: "Luke 2:9", text: "And behold, an Angel of our Lord stood beside them, and the brightness of God did shine round about them, and they feared with a great fear."),
            ScripturalVerse(reference: "Luke 2:10", text: "And the Angel said to them: Fear not; for behold I evangelize to you great joy, that shall be to all the people:"),
            ScripturalVerse(reference: "Luke 2:11", text: "Because this day is born to you a Saviour which is Christ our Lord, in the city of David."),
            ScripturalVerse(reference: "Luke 2:14", text: "Glory in the highest to God: and in earth peace to men of good will."),
            ScripturalVerse(reference: "Luke 2:19", text: "But Mary kept all these words, conferring them in her heart."),
        ],
        "joyful_4": [
            ScripturalVerse(reference: "Luke 2:22", text: "And after the days were fully ended of her purification according to the law of Moyses, they carried him into Jerusalem, to present him to our Lord"),
            ScripturalVerse(reference: "Luke 2:25", text: "And behold there was a man in Jerusalem named Simeon, and this man was just and religious, expecting the consolation of Israel: and the Holy Ghost was in him."),
            ScripturalVerse(reference: "Luke 2:26", text: "And he had received an answer of the Holy Ghost, that he should not see death unless he saw first the Christ of our Lord."),
            ScripturalVerse(reference: "Luke 2:27", text: "And he came in Spirit into the temple. And when his parents brought in the child Jesus, to do according to the custom of the Law for him,"),
            ScripturalVerse(reference: "Luke 2:28", text: "He also took him into his arms, and blessed God, and said:"),
            ScripturalVerse(reference: "Luke 2:29", text: "Now Thou doest dismiss thy servant O Lord, according to thy word in peace."),
            ScripturalVerse(reference: "Luke 2:30", text: "Because mine eyes have seen thy Salvation,"),
            ScripturalVerse(reference: "Luke 2:32", text: "A light to the revelation of the Gentiles, and the glory of thy people Israel."),
            ScripturalVerse(reference: "Luke 2:34", text: "And Simeon blessed them, and said to Mary his mother: Behold this is set unto the ruin, and unto the resurrection of many in Israel, and for a sign which shall be contradicted,"),
            ScripturalVerse(reference: "Luke 2:35", text: "And thine own soul shall a sword pierce, that out of many hearts cogitations may be revealed."),
        ],
        "joyful_5": [
            ScripturalVerse(reference: "Luke 2:42", text: "And when he was twelve years old, they going up into Jerusalem according to the custom of the festival day;"),
            ScripturalVerse(reference: "Luke 2:43", text: "And having ended the days, when they returned, the child Jesus remained in Jerusalem: and his parents knew it not."),
            ScripturalVerse(reference: "Luke 2:45", text: "And not finding him, they returned into Jerusalem, seeking him."),
            ScripturalVerse(reference: "Luke 2:46", text: "And it came to pass, after three days they found him in the temple sitting in the midst of the Doctors, hearing them and asking them."),
            ScripturalVerse(reference: "Luke 2:47", text: "And all were astonished that heard him, upon his wisdom and answers."),
            ScripturalVerse(reference: "Luke 2:48", text: "And seeing him, they wondered. And his mother said to him: Son, why hast thou so done to us? Behold thy father and I sorrowing did seek thee."),
            ScripturalVerse(reference: "Luke 2:49", text: "And he said to them: What is it that you sought me? Did you not know, that I must be about those things which are my Father's?"),
            ScripturalVerse(reference: "Luke 2:50", text: "And they understood not the word that he spake unto them."),
            ScripturalVerse(reference: "Luke 2:51", text: "And he went down with them, and came to Nazareth; and was subject to them. And his mother kept all these words in her heart."),
            ScripturalVerse(reference: "Luke 2:52", text: "And Jesus proceeded in wisdom and age, and grace with God and men."),
        ],
        "sorrowful_1": [
            ScripturalVerse(reference: "Matthew 26:36", text: "Then Jesus cometh with them into a village called Gethsemani: and he said to his Disciples: Sit you here till I go yonder, and pray."),
            ScripturalVerse(reference: "Matthew 26:37", text: "And taking to him Peter and the two sons of Zebedee, he began to wax sorrowful and to be sad."),
            ScripturalVerse(reference: "Matthew 26:38", text: "Then he saith to them: My soul is sorrowful even unto death: stay here, and watch with me."),
            ScripturalVerse(reference: "Matthew 26:39", text: "And being gone forward a little, he fell upon his face, praying, and saying: My Father, if it be possible, let this chalice pass from me. Nevertheless not as I will, but as thou."),
            ScripturalVerse(reference: "Matthew 26:40", text: "And he cometh to his Disciples, and findeth them sleeping, and he saith to Peter: Even so? Could you not watch one hour with me?"),
            ScripturalVerse(reference: "Matthew 26:41", text: "Watch ye, and pray that ye enter not into tentation. The Spirit indeed is prompt, but the flesh weak."),
            ScripturalVerse(reference: "Matthew 26:42", text: "Again the second time he went, and prayed, saying: My Father, if this chalice may not pass, but I must drink it, thy will be done."),
            ScripturalVerse(reference: "Luke 22:43", text: "And there appeared to him an Angel from Heaven, strengthening him. And being in an agony, he prayed the longer."),
            ScripturalVerse(reference: "Luke 22:44", text: "And his sweat became as drops of blood trickling down upon the earth."),
            ScripturalVerse(reference: "Matthew 26:46", text: "Rise, let us go: behold he approacheth that shall betray me."),
        ],
        "sorrowful_2": [
            ScripturalVerse(reference: "Luke 23:4", text: "And Pilate said to the chief Priests and multitudes: I find no cause in this man."),
            ScripturalVerse(reference: "Luke 23:16", text: "I will chasten him therefore and dismiss him."),
            ScripturalVerse(reference: "Matthew 27:24", text: "And Pilate seeing that he nothing prevailed, but rather tumult was toward; taking water he washed his hands before the People, saying: I am innocent of the blood of this just man: look you to it."),
            ScripturalVerse(reference: "Matthew 27:26", text: "Then he released to them Barabbas, and having scourged Jesus, delivered him unto them for to be crucified."),
            ScripturalVerse(reference: "Isaias 53:3", text: "Despised, and most abject of men, a man of sorrows, and knowing infirmity: and his look as it were hid and despised, whereupon neither have we esteemed him."),
            ScripturalVerse(reference: "Isaias 53:4", text: "He surely hath born our infirmities, and our sorrows he hath carried: and we have thought him as it were a leper, and strucken of God, and humbled."),
            ScripturalVerse(reference: "Isaias 53:5", text: "But he was wounded for our iniquities, he was broken for our sins: the discipline of our peace upon him, and with the wail of his stripe we are healed."),
            ScripturalVerse(reference: "Isaias 53:6", text: "All we have strayed as sheep, every one hath declined into his own way: and our Lord hath put upon him the iniquity of all us."),
            ScripturalVerse(reference: "Isaias 53:7", text: "He was offered because himself would, and opened not his mouth: as a sheep to slaughter shall he be led, and as a lamb before his shearer, he shall be dumb, and shall not open his mouth:"),
            ScripturalVerse(reference: "1 Peter 2:24", text: "Who himself bare our sins in his body upon the tree: that dead to sins, we may live to justice. By whose stripes you are healed."),
        ],
        "sorrowful_3": [
            ScripturalVerse(reference: "Matthew 27:27", text: "Then the President's soldiers taking Jesus into the Palace, gathered together unto him the whole band:"),
            ScripturalVerse(reference: "Matthew 27:28", text: "And stripping him, put a scarlet cloak about him."),
            ScripturalVerse(reference: "Matthew 27:29", text: "And platting a crown of thorns, put it upon his head, and a reed in his right hand. And bowing the knee before him, they mocked him, saying: Hail King of the Jews."),
            ScripturalVerse(reference: "Matthew 27:30", text: "And spitting upon him, they took the reed, and smote his head."),
            ScripturalVerse(reference: "Isaias 50:6", text: "I have given my body to the strikers, and my cheeks to the pluckers: I have not turned away my face from the rebukers and spitters."),
            ScripturalVerse(reference: "John 19:5", text: "Jesus therefore went forth carrying the crown of thorns, and the purple vestiment. And he saith to them: Lo the man."),
            ScripturalVerse(reference: "John 19:6", text: "When the chief Priests therefore and the ministers had seen him, they cried, saying: Crucify, crucify him. Pilate saith to them: Take him you, and crucify him. For I find no cause in him."),
            ScripturalVerse(reference: "John 19:14", text: "And it was the Parasceve of Pasch, about the sixth hour, and he saith to the Jews: Lo your King."),
            ScripturalVerse(reference: "John 19:15", text: "But they cried: Away, away with him, crucify him. Pilate saith to them: Shall I crucify your King? The chief Priests answered: We have no King, but Cæsar."),
            ScripturalVerse(reference: "Matthew 27:31", text: "And after they had mocked him, they took off the cloak from him, and put on him his own garments, and led him away to crucify him."),
        ],
        "sorrowful_4": [
            ScripturalVerse(reference: "John 19:16", text: "Then therefore he delivered him unto them for to be crucified. And they took Jesus, and led him forth."),
            ScripturalVerse(reference: "John 19:17", text: "And bearing his own cross he went forth into that which is called the place of Calvary, in Hebrew Golgotha."),
            ScripturalVerse(reference: "Luke 23:26", text: "And when they led him, they took one Simon of Cyrene coming from the country: and they laid the Cross upon him to carry after Jesus."),
            ScripturalVerse(reference: "Luke 23:27", text: "And there followed him a great multitude of people, and of women which bewailed and lamented him."),
            ScripturalVerse(reference: "Luke 23:28", text: "But Jesus turning to them, said: Daughters of Jerusalem, weep not upon me, but weep upon yourselves, and upon your children."),
            ScripturalVerse(reference: "Luke 23:31", text: "For if in the green wood they do these things, in the dry what shall be done?"),
            ScripturalVerse(reference: "Lamentations 1:12", text: "O all ye that pass by the way, attend, and see if there be sorrow like to my sorrow: because he hath made vintage of me, as our Lord hath spoken in the day of the wrath of his fury."),
            ScripturalVerse(reference: "Luke 9:23", text: "And he said to all: If any man will come after me, let him deny himself, and take up his cross daily, and follow me."),
            ScripturalVerse(reference: "Matthew 11:29", text: "Take up my yoke upon you, and learn of me, because I am meek, and humble of heart: and you shall find rest to your souls."),
            ScripturalVerse(reference: "Matthew 11:30", text: "For my yoke is sweet, and my burden light."),
        ],
        "sorrowful_5": [
            ScripturalVerse(reference: "Luke 23:33", text: "And after they came to the place which is called Calvary, there they crucified him: and the thieves, one on the right hand and the other on the left."),
            ScripturalVerse(reference: "Luke 23:34", text: "And Jesus said: Father, forgive them, for they know not what they do. But they dividing his garments, did cast lots."),
            ScripturalVerse(reference: "Luke 23:42", text: "And he said to Jesus: Lord, remember me when thou shalt come into thy Kingdom."),
            ScripturalVerse(reference: "Luke 23:43", text: "And Jesus said to him: Amen I say to thee; this day thou shalt be with me in Paradise."),
            ScripturalVerse(reference: "John 19:26", text: "When Jesus therefore had seen his mother and the Disciple standing whom he loved, he saith to his mother: Woman, behold thy son."),
            ScripturalVerse(reference: "John 19:27", text: "After that, he saith to the Disciple: Behold thy mother. And from that hour the Disciple took her to his own."),
            ScripturalVerse(reference: "Matthew 27:46", text: "And about the ninth hour Jesus cried with a mighty voice, saying: Eli, Eli, lamma-sabacthani? that is, My God, my God, why hast thou forsaken me?"),
            ScripturalVerse(reference: "John 19:28", text: "Afterward Jesus knowing that all things were now consummate, that the scripture might be fulfilled, he saith, I thirst."),
            ScripturalVerse(reference: "John 19:30", text: "Jesus therefore when he had taken the vinegar, said: It is consummate. And bowing his head, he gave up the ghost."),
            ScripturalVerse(reference: "Luke 23:46", text: "And Jesus crying with a loud voice, said: Father, into thy hands I commend my Spirit. And saying this, he gave up the ghost."),
        ],
        "glorious_1": [
            ScripturalVerse(reference: "Matthew 28:1", text: "And in the evening of the Sabboth which dawneth on the first of the Sabboth, came Mary Magdalene, and the other Mary to see the sepulchre."),
            ScripturalVerse(reference: "Matthew 28:2", text: "And behold there was made a great earth-quake. For an Angel of our Lord descended from Heaven: and coming, rolled back the stone, and sat upon it:"),
            ScripturalVerse(reference: "Matthew 28:5", text: "And the Angel answering said to the women: Fear not you. For I know that you seek Jesus that was crucified."),
            ScripturalVerse(reference: "Matthew 28:6", text: "He is not here, for he is risen, as he said. Come, and see the place where our Lord was laid."),
            ScripturalVerse(reference: "Luke 24:5", text: "And when they feared and cast down their countenance toward the ground, they said unto them: Why seek you the living with the dead?"),
            ScripturalVerse(reference: "John 20:16", text: "Jesus saith to her: Mary. She turning saith to him: Rabboni (which is to say, Master.)"),
            ScripturalVerse(reference: "John 20:19", text: "Therefore when it was late that day, the first of the Sabboths, and the doors were shut, where the Disciples were gathered together for fear of the Jews, Jesus came and stood in the midst, and saith to them: Peace be to you."),
            ScripturalVerse(reference: "John 20:27", text: "Then he saith to Thomas: Put in thy finger hither, and see my hands, and bring hither thy hand, and put it into my side; and be not incredulous but faithful."),
            ScripturalVerse(reference: "John 20:29", text: "Jesus saith to him: Because thou hast seen me, Thomas, thou hast believed: Blessed are they that have not seen and have believed."),
            ScripturalVerse(reference: "Romans 6:9", text: "Knowing that Christ rising again from the dead, now dieth no more, death shall no more have dominion over him."),
        ],
        "glorious_2": [
            ScripturalVerse(reference: "John 14:2", text: "In my Father's house there be many mansions. If not, I would have told you, Because I go to prepare you a place."),
            ScripturalVerse(reference: "John 14:3", text: "And if I go, and prepare you a place: I come again and will take you to myself, that where I am, you also may be."),
            ScripturalVerse(reference: "Matthew 28:18", text: "And Jesus coming near spake unto them, saying: All power is given to me in Heaven and in earth."),
            ScripturalVerse(reference: "Matthew 28:19", text: "Going therefore teach ye all Nations: Baptizing Them in The Name of The Father, And of The Son, And of The Holy Ghost,"),
            ScripturalVerse(reference: "Matthew 28:20", text: "Teaching them to observe all things whatsoever I have commanded you: and behold I am with you all days, even to the consummation of the world."),
            ScripturalVerse(reference: "Mark 16:15", text: "And he said to them: Going into the whole world preach the Gospel to all creatures."),
            ScripturalVerse(reference: "Acts 1:9", text: "And when he had said these things, in their sight he was elevated: and a cloud received him out of their sight."),
            ScripturalVerse(reference: "Acts 1:10", text: "And when they beheld him going into Heaven, behold two men stood beside them in white garments,"),
            ScripturalVerse(reference: "Acts 1:11", text: "Who also said: Ye men of Galilee, why stand you looking into Heaven? This Jesus which is assumpted from you into Heaven, shall so come as you have seen him going into Heaven."),
            ScripturalVerse(reference: "Mark 16:19", text: "And so our Lord Jesus after he spake unto them, was assumpted into Heaven, and sat on the right hand of God."),
        ],
        "glorious_3": [
            ScripturalVerse(reference: "John 14:16", text: "And I will ask the Father, and he will give you another Paraclete, that he may abide with you for ever,"),
            ScripturalVerse(reference: "John 14:26", text: "But the Paraclete the Holy Ghost, whom the Father will send in my name, he shall teach you all things, and suggest unto you all things whatsoever I shall say to you."),
            ScripturalVerse(reference: "Acts 1:14", text: "All these were persevering with one mind in prayer with the women and Mary the mother of Jesus, and his brethren."),
            ScripturalVerse(reference: "Acts 2:1", text: "And when the days of Pentecost were accomplished, they were all together in one place:"),
            ScripturalVerse(reference: "Acts 2:2", text: "And suddenly there was made a sound from Heaven, as of a vehement wind coming, and it filled the whole house where they were sitting."),
            ScripturalVerse(reference: "Acts 2:3", text: "And there appeared to them parted tongues as it were of fire, and it sat upon every one of them:"),
            ScripturalVerse(reference: "Acts 2:4", text: "And they were all replenished with the Holy Ghost, and they began to speak with diverse tongues, according as the Holy Ghost gave them to speak."),
            ScripturalVerse(reference: "Acts 2:38", text: "But Peter said to them, do penance, and be every one of you baptized in the name of Jesus Christ for remission of your sins; and you shall receive the gift of the Holy Ghost."),
            ScripturalVerse(reference: "Acts 2:41", text: "They therefore that received his word, were baptized: and there were added in that day about three thousand souls."),
            ScripturalVerse(reference: "Romans 5:5", text: "And hope confoundeth not: because the charity of God is poured forth in our hearts, by the Holy Ghost which is given us."),
        ],
        "glorious_4": [
            ScripturalVerse(reference: "Canticles 2:10", text: "Behold my beloved speaketh to me: Arise, make haste my love, my dove, my beautiful one, and come."),
            ScripturalVerse(reference: "Canticles 2:11", text: "For winter is now past, the rain is gone, and departed."),
            ScripturalVerse(reference: "Canticles 2:12", text: "The flowers have appeared in our land, the time of pruning is come: the voice of the turtle-dove is heard in our land:"),
            ScripturalVerse(reference: "Canticles 4:7", text: "Thou art all fair o my love, and there is not a spot in thee."),
            ScripturalVerse(reference: "Psalm 131:8", text: "Arise Lord into thy rest, thou, and the ark of thy sanctification."),
            ScripturalVerse(reference: "Judith 13:23", text: "Moreover Ozias the Prince of the people of Israel, said to her: Blessed art thou daughter of our Lord the high God, above all women upon the earth."),
            ScripturalVerse(reference: "Luke 1:48", text: "Because he hath regarded the humility of his handmaid; for behold from hence forth all generations shall call me blessed."),
            ScripturalVerse(reference: "Luke 1:49", text: "Because he that is mighty hath done great things to me: and holy is his name."),
            ScripturalVerse(reference: "1 Corinthians 15:54", text: "And when this mortal hath done on immortality, then shall come to pass the saying that is written: Death is swallowed up in victory."),
            ScripturalVerse(reference: "Apocalypse 21:4", text: "And God shall wipe away all tears from their eyes: and death shall be no more, nor mourning, nor crying, neither shall there be sorrow any more, which first things, are gone."),
        ],
        "glorious_5": [
            ScripturalVerse(reference: "Apocalypse 12:1", text: "And a great sign appeared in heaven; a woman clothed with the sun, and the moon under her feet, and on her head a crown of twelve stars:"),
            ScripturalVerse(reference: "Canticles 4:8", text: "Come from Libanus my spouse, come from Libanus, come: thou shalt be crowned from the head of Amana, from the top of Sanir and Hermon, from the dens of lions, from the mountains of leopards."),
            ScripturalVerse(reference: "Psalm 44:11", text: "The Queen stood on thy right hand in golden raiment: compassed with variety. Hear daughter, and see, and incline thine ear: and forget thy people, and the house of thy father."),
            ScripturalVerse(reference: "Psalm 44:12", text: "And the King will covet thy beauty: because he is the Lord thy God, and they shall adore him."),
            ScripturalVerse(reference: "Judith 15:10", text: "Who when she was come out to him, they all blessed her with one voice, saying: Thou art the glory of Jerusalem, thou the joy of Israel, thou the honour of our people:"),
            ScripturalVerse(reference: "Ecclesiasticus 24:17", text: "I am exalted as a cedar in Libanus, and as a cypress tree in mount Sion."),
            ScripturalVerse(reference: "Ecclesiasticus 24:24", text: "I am the mother of beautiful love, and of fear, and of knowledge, and of holy hope."),
            ScripturalVerse(reference: "Proverbs 8:35", text: "He that shall find me shall find life, and shall draw salvation of our Lord:"),
            ScripturalVerse(reference: "Luke 1:52", text: "He hath deposed the mighty from their seat, and hath exalted the humble."),
            ScripturalVerse(reference: "James 1:12", text: "Blessed is the man that suffereth tentation: for when he hath been proved, he shall receive the crown of life, which God hath promised to them that love him."),
        ],
        "luminous_1": [
            ScripturalVerse(reference: "Matthew 3:13", text: "Then cometh Jesus from Galilee to Jordan, unto John, to be baptized of him."),
            ScripturalVerse(reference: "Matthew 3:14", text: "But John stayed him, saying: I ought to be baptized of thee, and comest thou to me?"),
            ScripturalVerse(reference: "Matthew 3:15", text: "And Jesus answering, said to him: Suffer me for this time. For so it becometh us to fulfill all justice. Then he suffered him."),
            ScripturalVerse(reference: "Matthew 3:16", text: "And Jesus being baptized, forthwith came out of the water: and lo the Heavens were opened to him: and he saw the Spirit of God descending as a dove, and coming upon him."),
            ScripturalVerse(reference: "Matthew 3:17", text: "And behold a voice from Heaven saying: This is my beloved Son, in whom I am well pleased."),
            ScripturalVerse(reference: "John 1:29", text: "The next day John saw Jesus coming to him, and he saith: Behold the lamb of God, behold him that taketh away the sin of the world."),
            ScripturalVerse(reference: "John 1:32", text: "And John gave testimony, saying: That I saw the Spirit descending as a dove from Heaven, and he remained upon him."),
            ScripturalVerse(reference: "Isaias 42:1", text: "Behold my servant, I will receive him: mine elect, my soul hath pleased it-self in him: I have given my spirit upon him, he shall bring forth judgement to the Gentiles."),
            ScripturalVerse(reference: "John 3:5", text: "Jesus answered: Amen, Amen I say to thee, unless a man be born again of water and the Spirit, he cannot enter into the Kingdom of God."),
            ScripturalVerse(reference: "Acts 10:38", text: "Jesus of Nazareth how God anointed him with the Holy Ghost and with power, who went throughout doing good and healing all that were oppressed of the devil, because God was with him."),
        ],
        "luminous_2": [
            ScripturalVerse(reference: "John 2:1", text: "And the third day there was a marriage made in Cana of Galilee: and the mother of Jesus was there."),
            ScripturalVerse(reference: "John 2:2", text: "And Jesus also was called, and his Disciples to the marriage."),
            ScripturalVerse(reference: "John 2:3", text: "And the wine failing, the mother of Jesus saith to him: They have no wine."),
            ScripturalVerse(reference: "John 2:4", text: "And Jesus saith to her: What is to me and thee woman? My hour cometh not yet."),
            ScripturalVerse(reference: "John 2:5", text: "His mother saith to the ministers: Whatsoever he shall say to you, do ye."),
            ScripturalVerse(reference: "John 2:6", text: "And there were set there six water-pots of stone, according to the purification of the Jews, holding every one two or three measures."),
            ScripturalVerse(reference: "John 2:7", text: "Jesus saith to them: Fill the water-pots with water. And they filled them up to the top."),
            ScripturalVerse(reference: "John 2:8", text: "And Jesus saith to them: Draw now, and carry to the chief steward. And they carried it."),
            ScripturalVerse(reference: "John 2:9-10", text: "And after the chief steward tasted the water made wine, and knew not whence it was, but the ministers knew that had drawn the water; the chief steward calleth the bridegroom, and saith to him: Every man first setteth the good wine, and when they have well drunk, then that which is worse. But thou hast kept the good wine until now."),
            ScripturalVerse(reference: "John 2:11", text: "This beginning of miracles did Jesus in Cana of Galilee: and he manifested his glory, and his Disciples believed in him."),
        ],
        "luminous_3": [
            ScripturalVerse(reference: "Mark 1:14", text: "And after that John was delivered up, Jesus came into Galilee, preaching the Gospel of the Kingdom of God,"),
            ScripturalVerse(reference: "Mark 1:15", text: "And saying: That the time is fulfilled, and the Kingdom of God is at hand: be penitent, and believe the Gospel."),
            ScripturalVerse(reference: "Matthew 5:3", text: "Blessed are the poor in spirit: for theirs is the Kingdom of Heaven."),
            ScripturalVerse(reference: "Matthew 5:8", text: "Blessed are the clean of heart: for they shall see God."),
            ScripturalVerse(reference: "Matthew 6:33", text: "Seek therefore first the Kingdom of God, and the justice of him, and all these things shall be given you besides."),
            ScripturalVerse(reference: "Matthew 13:44", text: "The Kingdom of Heaven is like a treasure hidden in a field. Which a man having found, did hide it, and for joy thereof goeth, and selleth all that he hath, and buyeth that field."),
            ScripturalVerse(reference: "Matthew 11:28", text: "Come ye to me all that labour, and are burdened, and I will refresh you."),
            ScripturalVerse(reference: "Luke 17:21", text: "Neither shall they say: Lo here, or lo there. For lo the Kingdom of God is within you."),
            ScripturalVerse(reference: "John 8:12", text: "Again therefore Jesus spake to them, saying: I am the light of the world: he that followeth me, walketh not in darkness, but shall have the light of life."),
            ScripturalVerse(reference: "Matthew 9:35", text: "And Jesus went about all the cities, and towns, teaching in their Synagogues, and preaching the Gospel of the Kingdom, and curing every disease, and every infirmity."),
        ],
        "luminous_4": [
            ScripturalVerse(reference: "Matthew 17:1", text: "And after six days Jesus taketh unto him Peter, and James, and John his brother, and bringeth them into a high mountain apart:"),
            ScripturalVerse(reference: "Matthew 17:2", text: "And he was transfigured before them. And his face did shine as the sun: and his garments became white as snow."),
            ScripturalVerse(reference: "Luke 9:30", text: "And behold two men talked with him. And they were Moyses and Elias,"),
            ScripturalVerse(reference: "Luke 9:31", text: "Appearing in majesty. And they told his decease that he should accomplish in Jerusalem."),
            ScripturalVerse(reference: "Matthew 17:4", text: "And Peter answering, said to Jesus: Lord, it is good for us to be here: if thou wilt, let us make here three tabernacles, one for thee, and one for Moyses, and one for Elias."),
            ScripturalVerse(reference: "Matthew 17:5", text: "And as he was yet speaking, behold a bright cloud overshadowed them. And lo a voice out of the cloud, saying: This is my wellbeloved Son, in whom I am well pleased: hear ye him."),
            ScripturalVerse(reference: "Matthew 17:6", text: "And the Disciples hearing it, fell upon their face, and were sore afraid."),
            ScripturalVerse(reference: "Matthew 17:7", text: "And Jesus came and touched them: and he said to them: Arise, and fear not."),
            ScripturalVerse(reference: "2 Peter 1:17", text: "For, he receiving from God his Father honour and glory, this manner of voice coming down to him from the magnifical glory, This is my beloved Son in whom I have pleased myself, hear him."),
            ScripturalVerse(reference: "John 1:14", text: "And The Word Was Made Flesh, and dwelt in us (and we saw the glory of him, glory as it were of the Only-begotten of the Father) full of grace and verity."),
        ],
        "luminous_5": [
            ScripturalVerse(reference: "John 13:1", text: "And before the festival day of Pasch, Jesus knowing that his hour was come that he should pass out of this world to his Father: whereas he had loved his that were in the world, unto the end he loved them."),
            ScripturalVerse(reference: "John 6:35", text: "And Jesus said to them: I am the bread of life, he that cometh to me, shall not hunger; and he that believeth in me, shall never thirst."),
            ScripturalVerse(reference: "John 6:51", text: "I am the living bread, that came down from Heaven. If any man eat of this bread, he shall live for ever: and the bread which I will give, is my flesh for the life of the world."),
            ScripturalVerse(reference: "John 6:55", text: "For my flesh, is meat indeed: and my blood is drink indeed."),
            ScripturalVerse(reference: "John 6:57", text: "As the living Father hath sent me, and I live by the Father: and he that eateth me, the same also shall live by me."),
            ScripturalVerse(reference: "Matthew 26:26", text: "And whiles they were at supper, Jesus took bread, and blessed, and brake: and he gave to his Disciples, and said: Take ye, and eat: This is my Body."),
            ScripturalVerse(reference: "Matthew 26:27", text: "And taking the chalice, he gave thanks: and gave to them, saying: Drink ye all of this."),
            ScripturalVerse(reference: "Matthew 26:28", text: "For This is my Blood of The New Testament, Which Shall be Shed For Many Unto Remission of Sins."),
            ScripturalVerse(reference: "Luke 22:19", text: "And taking bread, he gave thanks, and brake; and gave to them, saying: This is my Body Which is Given For You. Do this for a commemoration of me."),
            ScripturalVerse(reference: "1 Corinthians 11:26", text: "For as often as you shall eat this bread, and drink the chalice, you shall shew the death of our Lord, until he come."),
        ],
        "seven_sorrows_1": [
            ScripturalVerse(reference: "Luke 2:25", text: "And behold there was a man in Jerusalem named Simeon, and this man was just and religious, expecting the consolation of Israel: and the Holy Ghost was in him."),
            ScripturalVerse(reference: "Luke 2:26", text: "And he had received an answer of the Holy Ghost, that he should not see death unless he saw first the Christ of our Lord."),
            ScripturalVerse(reference: "Luke 2:27", text: "And he came in Spirit into the temple. And when his parents brought in the child Jesus, to do according to the custom of the Law for him,"),
            ScripturalVerse(reference: "Luke 2:28-29", text: "He also took him into his arms, and blessed God, and said: Now Thou doest dismiss thy servant O Lord, according to thy word in peace."),
            ScripturalVerse(reference: "Luke 2:33", text: "And his father and mother were marveling upon those things which were spoken concerning him."),
            ScripturalVerse(reference: "Luke 2:34", text: "And Simeon blessed them, and said to Mary his mother: Behold this is set unto the ruin, and unto the resurrection of many in Israel, and for a sign which shall be contradicted,"),
            ScripturalVerse(reference: "Luke 2:35", text: "And thine own soul shall a sword pierce, that out of many hearts cogitations may be revealed."),
        ],
        "seven_sorrows_2": [
            ScripturalVerse(reference: "Matthew 2:13", text: "And after they were departed, Behold an Angel of our Lord appeared in sleep to Joseph, saying: Arise, and take the child and his mother, and fly into Ægypt; and be there until I shall tell thee. For it will come to pass that Herod will seek the child to destroy him."),
            ScripturalVerse(reference: "Matthew 2:14", text: "Who arose, and took the child and his mother by night, and retired into Ægypt: and he was there until the death of Herod:"),
            ScripturalVerse(reference: "Matthew 2:15", text: "That it might be fulfilled which was spoken of our Lord by the Prophet, saying: Out of Ægypt have I called my Son."),
            ScripturalVerse(reference: "Matthew 2:16", text: "Then Herod perceiving that he was deluded by the Sages, was exceeding angry; and sending murdered all the men children that were in Bethlehem, and in all the borders thereof, from two year old and under, according to the time which he had diligently sought out of the Sages."),
            ScripturalVerse(reference: "Matthew 2:18", text: "A voice in Rama was heard, crying out and much wailing: Rachel bewailing her children, and would not be comforted, because they are not."),
            ScripturalVerse(reference: "Matthew 2:19-20", text: "But when Herod was dead, behold an Angel of our Lord appeared in sleep to Joseph in Ægypt. Saying: Arise, and take the child and his mother, and go into the land of Israel. For they are dead that sought the life of the child."),
            ScripturalVerse(reference: "Matthew 2:21", text: "Who arose, and took the child and his mother, and came into the land of Israel."),
        ],
        "seven_sorrows_3": [
            ScripturalVerse(reference: "Luke 2:43", text: "And having ended the days, when they returned, the child Jesus remained in Jerusalem: and his parents knew it not."),
            ScripturalVerse(reference: "Luke 2:44", text: "And thinking that he was in the company, they came a day's journey, and sought him among their kinsfolk and acquaintance."),
            ScripturalVerse(reference: "Luke 2:45", text: "And not finding him, they returned into Jerusalem, seeking him."),
            ScripturalVerse(reference: "Luke 2:46", text: "And it came to pass, after three days they found him in the temple sitting in the midst of the Doctors, hearing them and asking them."),
            ScripturalVerse(reference: "Luke 2:48", text: "And seeing him, they wondered. And his mother said to him: Son, why hast thou so done to us? Behold thy father and I sorrowing did seek thee."),
            ScripturalVerse(reference: "Luke 2:49", text: "And he said to them: What is it that you sought me? Did you not know, that I must be about those things which are my Father's?"),
            ScripturalVerse(reference: "Luke 2:51", text: "And he went down with them, and came to Nazareth; and was subject to them. And his mother kept all these words in her heart."),
        ],
        "seven_sorrows_4": [
            ScripturalVerse(reference: "Luke 23:26", text: "And when they led him, they took one Simon of Cyrene coming from the country: and they laid the Cross upon him to carry after Jesus."),
            ScripturalVerse(reference: "Luke 23:27", text: "And there followed him a great multitude of people, and of women which bewailed and lamented him."),
            ScripturalVerse(reference: "Luke 23:28", text: "But Jesus turning to them, said: Daughters of Jerusalem, weep not upon me, but weep upon yourselves, and upon your children."),
            ScripturalVerse(reference: "Lamentations 1:12", text: "O all ye that pass by the way, attend, and see if there be sorrow like to my sorrow: because he hath made vintage of me, as our Lord hath spoken in the day of the wrath of his fury."),
            ScripturalVerse(reference: "Lamentations 1:16", text: "Therefore am I weeping, and mine eye shedding tears: because a comforter is made far from me, converting my soul: my children are become desolate because the enemy hath prevailed."),
            ScripturalVerse(reference: "Lamentations 2:13", text: "Whereto shall I compare thee? Or whereto shall I liken thee o daughter of Jerusalem: whereto shall I make thee equal, and comfort thee o virgin daughter of Sion? For great is thy destruction as the sea: who shall heal thee?"),
            ScripturalVerse(reference: "Isaias 53:4", text: "He surely hath born our infirmities, and our sorrows he hath carried: and we have thought him as it were a leper, and strucken of God, and humbled."),
        ],
        "seven_sorrows_5": [
            ScripturalVerse(reference: "John 19:18", text: "Where they crucified him, and with him two others, on the one side and on the other, and in the midst Jesus."),
            ScripturalVerse(reference: "John 19:25", text: "And there stood beside the cross of Jesus, his mother, and his mother's sister, Mary of Cleophas, and Mary Magdalene."),
            ScripturalVerse(reference: "John 19:26", text: "When Jesus therefore had seen his mother and the Disciple standing whom he loved, he saith to his mother: Woman, behold thy son."),
            ScripturalVerse(reference: "John 19:27", text: "After that, he saith to the Disciple: Behold thy mother. And from that hour the Disciple took her to his own."),
            ScripturalVerse(reference: "John 19:28", text: "Afterward Jesus knowing that all things were now consummate, that the scripture might be fulfilled, he saith, I thirst."),
            ScripturalVerse(reference: "John 19:30", text: "Jesus therefore when he had taken the vinegar, said: It is consummate. And bowing his head, he gave up the ghost."),
            ScripturalVerse(reference: "Luke 23:46", text: "And Jesus crying with a loud voice, said: Father, into thy hands I commend my Spirit. And saying this, he gave up the ghost."),
        ],
        "seven_sorrows_6": [
            ScripturalVerse(reference: "John 19:33", text: "But after they were come to Jesus, when they saw that he was dead, they did not break his legs,"),
            ScripturalVerse(reference: "John 19:34", text: "But one of the soldiers with a spear opened his side, and incontinent there came forth blood and water."),
            ScripturalVerse(reference: "John 19:37", text: "And again another scripture saith: They shall look on him whom they pierced."),
            ScripturalVerse(reference: "John 19:38", text: "And after these things Joseph of Arimathæa (because he was a Disciple of Jesus, but secret for fear of the Jews) desired Pilate that he might take away the body of Jesus. And Pilate permitted. He came therefore, and took away the body of Jesus."),
            ScripturalVerse(reference: "John 19:39", text: "Nicodemus also came, he that at the first came to Jesus by night, bringing a mixture of myrrh and aloes, about an hundred pounds."),
            ScripturalVerse(reference: "Zacharias 12:10", text: "And I will pour out upon the house of David, and upon the inhabitants of Jerusalem the spirit of grace, and of prayers: and they shall look toward me, whom they pierced: and they shall lament him with lamentation as it were upon an only begotten, and they shall sorrow upon him, as the manner is to be sorrowful in the death of the first begotten."),
            ScripturalVerse(reference: "Lamentations 2:11", text: "Mine eyes have failed for tears, my bowels are troubled: my liver is poured out on the earth, for the destruction of the daughter of my people, when the little one, and the sucking fainted in the streets of the town."),
        ],
        "seven_sorrows_7": [
            ScripturalVerse(reference: "John 19:40", text: "They took therefore the body of Jesus, and bound it in linen cloths with the spices, as the manner is with the Jews to bury."),
            ScripturalVerse(reference: "John 19:41", text: "And there was in the place where he was crucified, a garden: and in the garden a new monument, wherein no man yet had been laid."),
            ScripturalVerse(reference: "John 19:42", text: "There therefore because of the Parasceve of the Jews, they laid Jesus, because the monument was hard by."),
            ScripturalVerse(reference: "Matthew 27:60", text: "And laid it in his own new monument, which he had hewed out in a rock. And he rolled a great stone to the door of the monument, and went his way."),
            ScripturalVerse(reference: "Matthew 27:61", text: "And there was there Mary Magdalene, and the other Mary, sitting over against the sepulchre."),
            ScripturalVerse(reference: "Luke 23:55", text: "And the women that were come with him from Galilee, following after, saw the monument, and how his body was laid."),
            ScripturalVerse(reference: "Luke 23:56", text: "And returning they prepared spices and ointments: and on the Sabboth they rested according to the commandment."),
        ],
    ]
}
