//
//  Chant.swift
//  Lumen Viae
//
//  The Chant Library's vocabulary. A chant is one recording and its score:
//  sung and engraved by Verbum Gloriae, a Spanish apostolate of Gregorian
//  chant, and bundled so it sounds in a chapel with no signal. The pieces
//  themselves — which chants, their titles, the prayers each is a sung
//  form of — are `ChantCatalogData.swift`, GENERATED by Tools/Chants.
//
//  Verbum Gloriae publishes under a copyleft licence: free to copy, adapt
//  and use for any purpose, no attribution required, so long as an
//  adaptation carries the same licence. The files here are adaptations
//  (the Ogg recordings re-encoded as AAC, the SVG scores rewritten as the
//  drawing the app recolours), so they carry it, and the app says so
//  wherever a chant plays (`ChantCatalog.credit`).
//

import Foundation
import CoreGraphics

// MARK: - ChantScorePart

/// One engraved stave of a chant's score. Most chants have one; a hymn
/// adds its versicle and collect, a litany one part per section.
struct ChantScorePart: Hashable {
    /// The bundled drawing, `<file>.lvscore` (see `ChantScoreDrawing`)
    let file: String
    /// What the part is, in Latin or in English ("Oremus. Deus qui corda")
    let caption: String
    /// Width over height of the engraving
    let aspectRatio: CGFloat
}

// MARK: - ChantLine

/// One sung line of a chant: its words, a plain English rendering, and
/// where it stands in the recording. Lines come from
/// `Tools/ChantLines/<chant id>.json`, derived from the bundled recording
/// and checked line by line before they are added; a chant without that
/// file has none, and every surface that steps by the line falls back to
/// the whole chant. No timing is ever guessed.
struct ChantLine: Hashable {
    let latin: String
    let english: String
    /// Seconds into the chant's recording
    let start: TimeInterval
    let end: TimeInterval
    /// The score part the line is engraved on, when the file names one
    var part: Int? = nil

    var length: TimeInterval { max(0, end - start) }
}

// MARK: - ChantGroup

/// A shelf of the library: Our Lady, the Blessed Sacrament, a season.
struct ChantGroup: Identifiable, Hashable {
    let id: String
    let title: String
    let note: String?
}

// MARK: - Chant

struct Chant: Identifiable, Hashable {
    let id: String
    let groupID: String
    let latinTitle: String
    let englishTitle: String
    /// The setting where a chant has more than one ("Simple tone")
    let setting: String?
    /// When it is sung, in one line
    let detail: String
    /// The app's own prayers this chant is a sung form of
    let prayerIDs: [String]
    /// Seconds, measured from the bundled file
    let duration: TimeInterval
    let score: [ChantScorePart]
    /// The chant's own page at Verbum Gloriae
    let sourceURL: URL
    /// Its sung lines, timed against the recording — empty until the
    /// chant's lines have been derived and checked (`ChantLine`)
    var lines: [ChantLine] = []

    /// Whether the chant can be stepped, repeated and practised a line
    /// at a time
    var hasLines: Bool { !lines.isEmpty }

    /// The line sounding at `time`, or the one just sung while the
    /// recording rests between two
    func lineIndex(at time: TimeInterval) -> Int? {
        guard !lines.isEmpty else { return nil }
        if let index = lines.lastIndex(where: { $0.start <= time + 0.05 }) { return index }
        return 0
    }

    /// The bundled recording. Resources are copied flat into the bundle.
    var audioURL: URL? {
        Bundle.main.url(forResource: id, withExtension: "m4a")
    }

    var group: ChantGroup? {
        ChantCatalog.groups.first { $0.id == groupID }
    }

    /// "4:08"
    var durationLabel: String {
        let whole = Int(duration.rounded())
        return "\(whole / 60):\(String(format: "%02d", whole % 60))"
    }

    /// The setting, where neither title already says it: a title naming
    /// its own setting is not also "· antiphon" beneath it, and Credo III
    /// is not "The Nicene Creed · credo iii".
    var distinctSetting: String? {
        guard let setting,
              !englishTitle.localizedCaseInsensitiveContains(setting),
              !latinTitle.localizedCaseInsensitiveContains(setting) else { return nil }
        return setting
    }

    /// The distinct setting as it reads after a "·" mid-line: "simple
    /// tone", "with alleluia", but a Mass by its name and number, "Mass
    /// VIII", never "mass viii"
    var settingMidLine: String? {
        guard let setting = distinctSetting else { return nil }
        let named = setting.split(separator: " ").contains { word in
            word.allSatisfy { "IVXLC".contains($0) }
        }
        return named ? setting : setting.lowercased()
    }

    /// The title with its setting, for a row that has room for one line:
    /// "Salve Regina · Simple tone", and Credo III alone, never twice
    var fullTitle: String {
        if let setting, !latinTitle.localizedCaseInsensitiveContains(setting) {
            return "\(latinTitle) · \(setting)"
        }
        return latinTitle
    }
}

// MARK: - ChantCatalog

/// Every chant the app carries, and the ways to find one. The data is in
/// the generated extension.
enum ChantCatalog {

    static func chant(_ id: String) -> Chant? {
        all.first { $0.id == id }
    }

    /// The chants that are a sung form of one of the app's prayers, in the
    /// catalog's order (so a simple tone comes before a solemn one).
    static func chants(forPrayer prayerID: String) -> [Chant] {
        all.filter { $0.prayerIDs.contains(prayerID) }
    }

    static func chants(in group: ChantGroup) -> [Chant] {
        all.filter { $0.groupID == group.id }
    }

    /// The other settings of the same prayer — the solemn tone beside the
    /// simple — for a chant's page to offer.
    static func otherSettings(of chant: Chant) -> [Chant] {
        guard !chant.prayerIDs.isEmpty else { return [] }
        return all.filter { other in
            other.id != chant.id && !Set(other.prayerIDs).isDisjoint(with: chant.prayerIDs)
        }
    }

    /// Chants whose Latin or English title holds `query`, accents and
    /// case aside.
    static func search(_ query: String) -> [Chant] {
        let needle = fold(query)
        guard !needle.isEmpty else { return [] }
        return all.filter { chant in
            fold(chant.latinTitle).contains(needle) || fold(chant.englishTitle).contains(needle)
        }
    }

    /// The antiphon of Our Lady the season sings tonight, in its simple
    /// tone — the library's first piece and the Chapel tile's until the
    /// reader chooses another.
    static func antiphonOfTheSeason(on date: Date = Date()) -> Chant? {
        chants(forPrayer: PrayerBook.antiphon(on: date).prayerID).first
    }

    private static func fold(_ text: String) -> String {
        text.folding(options: [.caseInsensitive, .diacriticInsensitive], locale: nil)
            .replacingOccurrences(of: "æ", with: "ae")
            .trimmingCharacters(in: .whitespacesAndNewlines)
    }

    // MARK: Credit

    /// Said wherever a chant plays. The licence asks for no attribution;
    /// the app gives it anyway, and says the files are shared on the same
    /// terms, which the licence does ask.
    static let credit = "Sung and engraved by Verbum Gloriae"
    static let licenceNote = "Shared under Verbum Gloriae's copyleft licence. The recordings here are re-encoded and the scores recoloured, and they carry the same licence."
    static let sourceSite = URL(string: "https://www.verbumgloriae.es")!
    static let licenceURL = URL(string: "https://www.verbumgloriae.es/licencia-copyleft/")!
}
